import {
  type AdminSettings,
  type ConsentRecord,
  type Customer,
  type EventLog,
  type HelpArticle,
  type Integration,
  type Order,
  type StageStep,
  type SupportTicket,
  type TestRun,
} from "@/lib/types";

export const DEFAULT_CUSTOMER_ID = "cust-ora-clinic";

export const onboardingSteps: StageStep[] = [
  {
    key: "basic-info",
    label: "1단계 기본 정보",
    description: "조직 정보와 기본 연결 환경을 확인합니다.",
  },
  {
    key: "privacy-consent",
    label: "2단계 개인정보 동의",
    description: "수집 목적과 동의 버전을 확인하고 제출합니다.",
  },
  {
    key: "kakao-connected",
    label: "3단계 카카오 연동",
    description: "채널 정보를 입력하고 연결 확인을 완료합니다.",
  },
  {
    key: "test-run",
    label: "4단계 테스트 실행",
    description: "실제 메시지 또는 연결 검사를 수행합니다.",
  },
  {
    key: "active",
    label: "5단계 활성화 완료",
    description: "운영 투입 상태를 확인하고 모니터링을 시작합니다.",
  },
];

export const customers: Customer[] = [
  {
    id: "cust-ora-clinic",
    name: "오라의원",
    industry: "의료",
    segment: "상담 예약 자동화",
    contact: {
      name: "김세림",
      email: "serim.kim@oraclinic.co.kr",
      phone: "010-4892-8201",
    },
    currentStage: "kakao-connected",
    portalStatus: "error",
    healthStatus: "warning",
    onboardingPercent: 62,
    kakaoStatus: "reauth-required",
    lastTestAt: "2026-04-12T14:32:00+09:00",
    recentErrorCount: 4,
    openTicketCount: 1,
    sourceFormId: "FF-2026-0412-0018",
    sourceFormLabel: "오라의원 접수 폼",
    sourceFormUrl: "https://intake.flowfit.mock/ora-clinic",
    recommendedAction: "카카오 채널을 다시 연결하고 테스트 메시지를 실행하세요.",
  },
  {
    id: "cust-hanul-mobility",
    name: "하늘모빌리티",
    industry: "모빌리티",
    segment: "렌탈 상담 자동화",
    contact: {
      name: "이준호",
      email: "juno.lee@hanulmobility.com",
      phone: "010-2384-1198",
    },
    currentStage: "active",
    portalStatus: "active",
    healthStatus: "healthy",
    onboardingPercent: 100,
    kakaoStatus: "connected",
    lastTestAt: "2026-04-13T09:11:00+09:00",
    recentErrorCount: 0,
    openTicketCount: 0,
    sourceFormId: "FF-2026-0318-0024",
    sourceFormLabel: "하늘모빌리티 신청 폼",
    sourceFormUrl: "https://intake.flowfit.mock/hanul-mobility",
    recommendedAction: "최근 24시간 운영은 정상입니다. 주간 로그 검토만 진행하면 됩니다.",
  },
  {
    id: "cust-daejin-logistics",
    name: "대진로지스",
    industry: "물류",
    segment: "출고 접수 자동화",
    contact: {
      name: "박민우",
      email: "mw.park@daejinlogis.co.kr",
      phone: "010-7782-2409",
    },
    currentStage: "privacy-consent",
    portalStatus: "connecting",
    healthStatus: "warning",
    onboardingPercent: 35,
    kakaoStatus: "disconnected",
    recentErrorCount: 1,
    openTicketCount: 1,
    sourceFormId: "FF-2026-0408-0003",
    sourceFormLabel: "대진로지스 접수 폼",
    sourceFormUrl: "https://intake.flowfit.mock/daejin-logistics",
    recommendedAction: "필수 개인정보 동의를 먼저 수집해야 다음 단계로 이동할 수 있습니다.",
  },
  {
    id: "cust-jayu-education",
    name: "자유에듀",
    industry: "교육",
    segment: "수강 상담 자동화",
    contact: {
      name: "한유리",
      email: "yuri.han@jayu-edu.kr",
      phone: "010-6629-4110",
    },
    currentStage: "test-run",
    portalStatus: "needs-test",
    healthStatus: "error",
    onboardingPercent: 78,
    kakaoStatus: "error",
    lastTestAt: "2026-04-12T16:41:00+09:00",
    recentErrorCount: 6,
    openTicketCount: 2,
    sourceFormId: "FF-2026-0329-0012",
    sourceFormLabel: "자유에듀 신청 폼",
    sourceFormUrl: "https://intake.flowfit.mock/jayu-education",
    recommendedAction: "카카오 앱 권한 부족이 반복되고 있어 관리자 검토가 필요합니다.",
  },
  {
    id: "cust-nara-retail",
    name: "나라리테일",
    industry: "리테일",
    segment: "매장 문의 자동화",
    contact: {
      name: "최다은",
      email: "daeun.choi@nara-retail.kr",
      phone: "010-9472-1874",
    },
    currentStage: "active",
    portalStatus: "active",
    healthStatus: "healthy",
    onboardingPercent: 100,
    kakaoStatus: "connected",
    lastTestAt: "2026-04-13T08:12:00+09:00",
    recentErrorCount: 1,
    openTicketCount: 0,
    sourceFormId: "FF-2026-0221-0007",
    sourceFormLabel: "나라리테일 접수 폼",
    sourceFormUrl: "https://intake.flowfit.mock/nara-retail",
    recommendedAction: "Webhook 타임아웃이 1건 있었으나 자동 복구되었습니다.",
  },
];

export const integrations: Integration[] = [
  {
    id: "int-ora-kakao",
    customerId: "cust-ora-clinic",
    type: "kakao",
    name: "카카오톡 채널",
    status: "reauth-required",
    description: "상담 접수와 예약 알림을 카카오 알림톡으로 발송합니다.",
    capabilities: ["예약 안내 발송", "접수 완료 알림", "상담 상태 업데이트"],
    channelName: "오라의원 상담채널",
    channelId: "ora-channel-29",
    senderProfile: "오라의원 알림",
    accessTokenMasked: "kko_live_****5ca9",
    callbackUrl: "https://ops.flowfit.mock/callbacks/kakao/ora-channel-29",
    lastValidatedAt: "2026-04-12T14:32:00+09:00",
    lastErrorCode: "KAKAO_TOKEN_EXPIRED",
    lastErrorMessage: "기존 카카오 연결 정보가 만료되어 메시지 전송 권한을 확인할 수 없습니다.",
    nextAction: "채널 정보를 확인하고 다시 연결 확인을 실행하세요.",
  },
  {
    id: "int-ora-email",
    customerId: "cust-ora-clinic",
    type: "email",
    name: "이메일",
    status: "connected",
    description: "담당자 승인 안내와 요약 리포트를 이메일로 발송합니다.",
    capabilities: ["승인 안내", "일일 리포트"],
    lastValidatedAt: "2026-04-13T08:20:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-ora-webhook",
    customerId: "cust-ora-clinic",
    type: "webhook",
    name: "웹훅",
    status: "error",
    description: "기존 접수 폼에서 신규 신청을 엔진으로 전달합니다.",
    capabilities: ["신청 이벤트 수신", "후처리 결과 전송"],
    callbackUrl: "https://ops.flowfit.mock/webhooks/ora-clinic",
    lastValidatedAt: "2026-04-13T09:04:00+09:00",
    lastErrorCode: "WEBHOOK_TIMEOUT",
    lastErrorMessage: "외부 접수 폼 응답이 10초 이상 지연되었습니다.",
    nextAction: "접수 폼 운영자에게 응답 지연 여부를 확인하세요.",
  },
  {
    id: "int-ora-crm",
    customerId: "cust-ora-clinic",
    type: "crm",
    name: "내부 CRM",
    status: "disconnected",
    description: "CRM 동기화는 차기 단계에서 연결 예정입니다.",
    capabilities: ["상담 이력 동기화"],
    nextAction: "필수 단계는 아니므로 후순위로 두어도 됩니다.",
  },
  {
    id: "int-hanul-kakao",
    customerId: "cust-hanul-mobility",
    type: "kakao",
    name: "카카오톡 채널",
    status: "connected",
    description: "렌탈 문의 접수와 상태 알림을 전송합니다.",
    capabilities: ["접수 알림", "방문 예약 안내"],
    channelName: "하늘모빌리티",
    channelId: "hanul-auto-33",
    senderProfile: "하늘모빌리티 알림",
    accessTokenMasked: "kko_live_****82aa",
    callbackUrl: "https://ops.flowfit.mock/callbacks/kakao/hanul-auto-33",
    lastValidatedAt: "2026-04-13T09:12:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-hanul-email",
    customerId: "cust-hanul-mobility",
    type: "email",
    name: "이메일",
    status: "connected",
    description: "일일 운영 요약을 발송합니다.",
    capabilities: ["운영 요약"],
    lastValidatedAt: "2026-04-13T08:52:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-hanul-webhook",
    customerId: "cust-hanul-mobility",
    type: "webhook",
    name: "웹훅",
    status: "connected",
    description: "신청 폼 결과를 실시간으로 받습니다.",
    capabilities: ["신청 수신", "처리 상태 전송"],
    callbackUrl: "https://ops.flowfit.mock/webhooks/hanul-mobility",
    lastValidatedAt: "2026-04-13T08:48:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-hanul-crm",
    customerId: "cust-hanul-mobility",
    type: "crm",
    name: "내부 CRM",
    status: "connected",
    description: "CRM에 자동으로 상담 내역을 기록합니다.",
    capabilities: ["상담 이력 동기화"],
    lastValidatedAt: "2026-04-13T08:40:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-daejin-kakao",
    customerId: "cust-daejin-logistics",
    type: "kakao",
    name: "카카오톡 채널",
    status: "disconnected",
    description: "출고 접수 안내를 위한 카카오 연동입니다.",
    capabilities: ["출고 알림", "상태 업데이트"],
    callbackUrl: "https://ops.flowfit.mock/callbacks/kakao/daejin",
    nextAction: "동의 제출 후 연결을 시작하세요.",
  },
  {
    id: "int-daejin-email",
    customerId: "cust-daejin-logistics",
    type: "email",
    name: "이메일",
    status: "connected",
    description: "담당자 확인 메일 발송",
    capabilities: ["접수 확인"],
    lastValidatedAt: "2026-04-13T10:01:00+09:00",
    nextAction: "정상 운영 중",
  },
  {
    id: "int-daejin-webhook",
    customerId: "cust-daejin-logistics",
    type: "webhook",
    name: "웹훅",
    status: "connecting",
    description: "기존 출고 신청 폼과 연결합니다.",
    capabilities: ["신청 폼 수신"],
    callbackUrl: "https://ops.flowfit.mock/webhooks/daejin-logistics",
    lastValidatedAt: "2026-04-13T09:55:00+09:00",
    nextAction: "접수 폼 연결이 완료되면 상태가 갱신됩니다.",
  },
  {
    id: "int-jayu-kakao",
    customerId: "cust-jayu-education",
    type: "kakao",
    name: "카카오톡 채널",
    status: "error",
    description: "상담 신청 및 합격 안내 발송",
    capabilities: ["신청 확인", "안내 메시지"],
    channelName: "자유에듀 알림",
    channelId: "jayu-ed-77",
    senderProfile: "자유에듀",
    accessTokenMasked: "kko_live_****3f9d",
    callbackUrl: "https://ops.flowfit.mock/callbacks/kakao/jayu-ed-77",
    lastValidatedAt: "2026-04-12T16:41:00+09:00",
    lastErrorCode: "KAKAO_SCOPE_MISSING",
    lastErrorMessage: "메시지 발송 scope가 없어 테스트 전송이 차단되었습니다.",
    nextAction: "권한이 포함된 앱으로 재승인해야 합니다.",
  },
  {
    id: "int-nara-kakao",
    customerId: "cust-nara-retail",
    type: "kakao",
    name: "카카오톡 채널",
    status: "connected",
    description: "매장 문의 접수와 응답 알림 발송",
    capabilities: ["접수 알림", "매장 배정 알림"],
    channelName: "나라리테일",
    channelId: "nara-rt-11",
    senderProfile: "나라리테일 알림",
    accessTokenMasked: "kko_live_****1ab2",
    callbackUrl: "https://ops.flowfit.mock/callbacks/kakao/nara-rt-11",
    lastValidatedAt: "2026-04-13T08:12:00+09:00",
    nextAction: "정상 운영 중",
  },
];

export const consentRecords: ConsentRecord[] = [
  {
    id: "consent-ora-2026-04",
    customerId: "cust-ora-clinic",
    version: "v2026.04",
    state: "active",
    agreedAt: "2026-04-10T11:14:00+09:00",
    agreedBy: "김세림",
    note: "필수 동의는 완료되었고 선택 동의는 마케팅 수신만 비활성화 상태입니다.",
    items: [
      {
        id: "consent-contact",
        label: "고객 연락처 및 신청 정보 수집",
        required: true,
        fields: ["성명", "휴대전화", "신청 내용"],
        purpose: "접수 처리, 상태 안내, 상담 이력 생성",
        retentionPeriod: "운영 종료 후 1년",
        checked: true,
      },
      {
        id: "consent-channel",
        label: "카카오 채널 발송을 위한 식별 정보 수집",
        required: true,
        fields: ["채널 ID", "발신 프로필", "연결 상태 정보"],
        purpose: "알림톡 발송 및 연결 검증",
        retentionPeriod: "연동 해지 후 90일",
        checked: true,
      },
      {
        id: "consent-marketing",
        label: "운영 고도화 제안 및 기능 안내 수신",
        required: false,
        fields: ["이메일", "담당자 부서"],
        purpose: "기능 업데이트와 운영 제안 안내",
        retentionPeriod: "동의 철회 시 즉시 파기",
        checked: false,
      },
    ],
  },
  {
    id: "consent-daejin-2026-04",
    customerId: "cust-daejin-logistics",
    version: "v2026.04",
    state: "not-submitted",
    note: "필수 동의가 제출되지 않아 카카오 연동 단계로 이동할 수 없습니다.",
    items: [
      {
        id: "consent-contact",
        label: "고객 연락처 및 신청 정보 수집",
        required: true,
        fields: ["성명", "휴대전화", "신청 내용"],
        purpose: "접수 처리와 상태 업데이트",
        retentionPeriod: "운영 종료 후 1년",
        checked: false,
      },
      {
        id: "consent-channel",
        label: "카카오 채널 발송을 위한 식별 정보 수집",
        required: true,
        fields: ["채널 ID", "발신 프로필", "연결 상태 정보"],
        purpose: "연동 검증 및 메시지 발송",
        retentionPeriod: "연동 해지 후 90일",
        checked: false,
      },
      {
        id: "consent-marketing",
        label: "운영 고도화 제안 및 기능 안내 수신",
        required: false,
        fields: ["이메일", "담당자 부서"],
        purpose: "기능 업데이트와 운영 제안 안내",
        retentionPeriod: "동의 철회 시 즉시 파기",
        checked: false,
      },
    ],
  },
  {
    id: "consent-jayu-2026-03",
    customerId: "cust-jayu-education",
    version: "v2026.03",
    state: "needs-renewal",
    agreedAt: "2026-03-02T15:00:00+09:00",
    agreedBy: "한유리",
    note: "현재 운영 정책이 v2026.04로 갱신되어 재동의가 권장됩니다.",
    items: [
      {
        id: "consent-contact",
        label: "고객 연락처 및 신청 정보 수집",
        required: true,
        fields: ["성명", "휴대전화", "신청 내용"],
        purpose: "접수 처리와 상태 업데이트",
        retentionPeriod: "운영 종료 후 1년",
        checked: true,
      },
      {
        id: "consent-channel",
        label: "카카오 채널 발송을 위한 식별 정보 수집",
        required: true,
        fields: ["채널 ID", "발신 프로필", "연결 상태 정보"],
        purpose: "연동 검증 및 메시지 발송",
        retentionPeriod: "연동 해지 후 90일",
        checked: true,
      },
      {
        id: "consent-marketing",
        label: "운영 고도화 제안 및 기능 안내 수신",
        required: false,
        fields: ["이메일", "담당자 부서"],
        purpose: "기능 업데이트와 운영 제안 안내",
        retentionPeriod: "동의 철회 시 즉시 파기",
        checked: true,
      },
    ],
  },
];

export const testRuns: TestRun[] = [
  {
    id: "testrun-ora-1",
    customerId: "cust-ora-clinic",
    type: "message",
    status: "failed",
    recipient: "010-2211-9988",
    message: "예약 알림 테스트 메시지",
    startedAt: "2026-04-12T14:31:30+09:00",
    finishedAt: "2026-04-12T14:32:00+09:00",
    responseTimeMs: 1460,
    logLines: [
      "카카오 연결 확인 시작",
      "기존 연결 정보 만료 감지",
      "검증 요청이 401로 종료됨",
    ],
    failureReason: "token-expired",
    retryable: true,
    integrationType: "kakao",
  },
  {
    id: "testrun-ora-2",
    customerId: "cust-ora-clinic",
    type: "connection-check",
    status: "success",
    recipient: "system-check",
    message: "웹훅 응답 확인",
    startedAt: "2026-04-13T08:57:30+09:00",
    finishedAt: "2026-04-13T08:58:02+09:00",
    responseTimeMs: 830,
    logLines: [
      "웹훅 헬스 체크 시작",
      "200 응답 수신",
      "응답 지연 0.83초",
    ],
    retryable: false,
    integrationType: "webhook",
  },
  {
    id: "testrun-hanul-1",
    customerId: "cust-hanul-mobility",
    type: "message",
    status: "success",
    recipient: "010-1111-2233",
    message: "렌탈 문의 테스트 메시지",
    startedAt: "2026-04-13T09:10:20+09:00",
    finishedAt: "2026-04-13T09:11:00+09:00",
    responseTimeMs: 910,
    logLines: [
      "카카오 연결 확인",
      "메시지 발송 완료",
      "수신 확인 콜백 도착",
    ],
    retryable: false,
    integrationType: "kakao",
  },
  {
    id: "testrun-jayu-1",
    customerId: "cust-jayu-education",
    type: "message",
    status: "failed",
    recipient: "010-4545-8899",
    message: "수강 상담 테스트 메시지",
    startedAt: "2026-04-12T16:40:20+09:00",
    finishedAt: "2026-04-12T16:41:00+09:00",
    responseTimeMs: 1280,
    logLines: [
      "카카오 연결 확인",
      "필수 scope 누락 확인",
      "메시지 발송 단계 진입 실패",
    ],
    failureReason: "insufficient-permission",
    retryable: true,
    integrationType: "kakao",
  },
  {
    id: "testrun-nara-1",
    customerId: "cust-nara-retail",
    type: "webhook-check",
    status: "success",
    recipient: "webhook-monitor",
    message: "매장 문의 폼 응답 확인",
    startedAt: "2026-04-13T08:11:12+09:00",
    finishedAt: "2026-04-13T08:12:00+09:00",
    responseTimeMs: 620,
    logLines: [
      "GET /health 호출",
      "200 응답",
      "자동 복구 상태 확인",
    ],
    retryable: false,
    integrationType: "webhook",
  },
];

export const orders: Order[] = [
  {
    id: "order-ora-001",
    customerId: "cust-ora-clinic",
    orderNumber: "ORA-260412-001",
    sourceFormLabel: "오라의원 접수 폼",
    status: "testing",
    createdAt: "2026-04-12T10:21:00+09:00",
    updatedAt: "2026-04-13T09:20:00+09:00",
    requestedItems: ["상담 접수 자동응답", "예약 확인 알림"],
    currentStepNote: "카카오 재인증 후 테스트 재실행 대기",
    requiredFixes: ["카카오 채널 재연결", "테스트 수신 번호 확인"],
  },
  {
    id: "order-ora-002",
    customerId: "cust-ora-clinic",
    orderNumber: "ORA-260410-004",
    sourceFormLabel: "오라의원 접수 폼",
    status: "reviewing",
    createdAt: "2026-04-10T16:00:00+09:00",
    updatedAt: "2026-04-10T18:30:00+09:00",
    requestedItems: ["야간 상담 알림"],
    currentStepNote: "운영 정책 검토 중",
  },
  {
    id: "order-ora-003",
    customerId: "cust-ora-clinic",
    orderNumber: "ORA-260401-002",
    sourceFormLabel: "오라의원 접수 폼",
    status: "activated",
    createdAt: "2026-04-01T13:10:00+09:00",
    updatedAt: "2026-04-04T17:40:00+09:00",
    requestedItems: ["기본 접수 알림"],
    currentStepNote: "운영 중",
  },
  {
    id: "order-jayu-001",
    customerId: "cust-jayu-education",
    orderNumber: "JAY-260329-001",
    sourceFormLabel: "자유에듀 신청 폼",
    status: "revision-requested",
    createdAt: "2026-03-29T11:24:00+09:00",
    updatedAt: "2026-04-12T16:50:00+09:00",
    requestedItems: ["수강 상담 접수 자동화"],
    requiredFixes: ["카카오 앱 재승인", "동의 문구 v2026.04 재제출"],
    currentStepNote: "권한 누락과 동의 버전 갱신 필요",
  },
];

export const eventLogs: EventLog[] = [
  {
    id: "log-ora-001",
    customerId: "cust-ora-clinic",
    customerName: "오라의원",
    occurredAt: "2026-04-13T09:04:00+09:00",
    integrationType: "webhook",
    eventName: "WebhookHealthCheckFailed",
    severity: "warning",
    status: "error",
    summary: "기존 접수 폼 응답이 지연되어 웹훅 헬스 체크가 실패했습니다.",
    cause: "외부 폼 서버 응답 지연",
    errorCode: "WEBHOOK_TIMEOUT",
    actor: "system",
    retryable: true,
    requestPayload: "{ \"url\": \"/health\", \"timeoutMs\": 10000 }",
    responsePayload: "{ \"status\": 504, \"message\": \"Gateway Timeout\" }",
  },
  {
    id: "log-ora-002",
    customerId: "cust-ora-clinic",
    customerName: "오라의원",
    occurredAt: "2026-04-12T14:32:00+09:00",
    integrationType: "kakao",
    eventName: "KakaoConnectionValidationFailed",
    severity: "critical",
    status: "error",
    summary: "카카오 연결 정보 만료로 연결 검증이 실패했습니다.",
    cause: "카카오 연결 정보 만료",
    errorCode: "KAKAO_TOKEN_EXPIRED",
    actor: "customer",
    retryable: true,
    requestPayload: "{ \"channelId\": \"ora-channel-29\" }",
    responsePayload: "{ \"code\": 401, \"message\": \"invalid token\" }",
  },
  {
    id: "log-ora-003",
    customerId: "cust-ora-clinic",
    customerName: "오라의원",
    occurredAt: "2026-04-10T11:14:00+09:00",
    eventName: "PrivacyConsentCompleted",
    severity: "success",
    status: "success",
    summary: "개인정보 동의가 v2026.04 버전으로 제출되었습니다.",
    actor: "customer",
    retryable: false,
  },
  {
    id: "log-hanul-001",
    customerId: "cust-hanul-mobility",
    customerName: "하늘모빌리티",
    occurredAt: "2026-04-13T09:11:00+09:00",
    integrationType: "kakao",
    eventName: "KakaoTestMessageSucceeded",
    severity: "success",
    status: "success",
    summary: "테스트 메시지가 정상 발송되었습니다.",
    actor: "customer",
    retryable: false,
  },
  {
    id: "log-daejin-001",
    customerId: "cust-daejin-logistics",
    customerName: "대진로지스",
    occurredAt: "2026-04-13T09:30:00+09:00",
    eventName: "PrivacyConsentMissing",
    severity: "warning",
    status: "warning",
    summary: "필수 개인정보 동의가 제출되지 않아 카카오 연동이 잠겨 있습니다.",
    cause: "필수 동의 미제출",
    errorCode: "CONSENT_REQUIRED",
    actor: "system",
    retryable: false,
  },
  {
    id: "log-jayu-001",
    customerId: "cust-jayu-education",
    customerName: "자유에듀",
    occurredAt: "2026-04-12T16:41:00+09:00",
    integrationType: "kakao",
    eventName: "KakaoPermissionDenied",
    severity: "critical",
    status: "error",
    summary: "카카오 앱에 메시지 발송 권한이 없어 테스트가 차단되었습니다.",
    cause: "scope 누락",
    errorCode: "KAKAO_SCOPE_MISSING",
    actor: "system",
    retryable: true,
    requestPayload: "{ \"scope\": [\"talk_message\"] }",
    responsePayload: "{ \"code\": 403, \"message\": \"scope missing\" }",
  },
  {
    id: "log-jayu-002",
    customerId: "cust-jayu-education",
    customerName: "자유에듀",
    occurredAt: "2026-04-12T16:50:00+09:00",
    eventName: "SupportTicketCreated",
    severity: "info",
    status: "info",
    summary: "권한 오류 대응을 위한 운영 티켓이 생성되었습니다.",
    actor: "admin",
    retryable: false,
  },
  {
    id: "log-nara-001",
    customerId: "cust-nara-retail",
    customerName: "나라리테일",
    occurredAt: "2026-04-13T07:21:00+09:00",
    integrationType: "webhook",
    eventName: "WebhookRecovered",
    severity: "success",
    status: "success",
    summary: "웹훅 응답 지연이 자동 복구되었습니다.",
    actor: "system",
    retryable: false,
  },
];

export const supportTickets: SupportTicket[] = [
  {
    id: "ticket-2401",
    customerId: "cust-ora-clinic",
    customerName: "오라의원",
    status: "in-progress",
    priority: "high",
    title: "카카오 재인증 필요",
    description: "카카오 연결 만료로 테스트 메시지가 실패하고 있습니다.",
    assignedTo: "박혜원",
    createdAt: "2026-04-12T14:35:00+09:00",
    lastUpdatedAt: "2026-04-13T09:18:00+09:00",
    category: "연동 오류",
    updates: [
      "고객에게 카카오 채널 재연결 절차를 안내했습니다.",
      "재연결 가이드 링크를 포함한 메시지를 발송했습니다.",
    ],
  },
  {
    id: "ticket-2402",
    customerId: "cust-daejin-logistics",
    customerName: "대진로지스",
    status: "open",
    priority: "medium",
    title: "개인정보 동의 미제출",
    description: "온보딩이 필수 동의 단계에서 멈춰 있습니다.",
    assignedTo: "김하늘",
    createdAt: "2026-04-13T09:40:00+09:00",
    lastUpdatedAt: "2026-04-13T09:40:00+09:00",
    category: "온보딩 지원",
    updates: ["고객사 담당자에게 동의 제출 요청 메일 발송 예정"],
  },
  {
    id: "ticket-2403",
    customerId: "cust-jayu-education",
    customerName: "자유에듀",
    status: "open",
    priority: "critical",
    title: "카카오 앱 권한 부족",
    description: "scope 누락으로 테스트와 운영 메시지 발송이 차단됩니다.",
    assignedTo: "오정민",
    createdAt: "2026-04-12T16:50:00+09:00",
    lastUpdatedAt: "2026-04-12T17:22:00+09:00",
    category: "권한/보안",
    updates: ["관리자 재승인 가이드를 발송했습니다."],
  },
  {
    id: "ticket-2404",
    customerId: "cust-jayu-education",
    customerName: "자유에듀",
    status: "on-hold",
    priority: "medium",
    title: "동의 버전 갱신 필요",
    description: "현재 동의 버전이 v2026.03이라 운영 정책과 불일치합니다.",
    assignedTo: "오정민",
    createdAt: "2026-04-11T10:14:00+09:00",
    lastUpdatedAt: "2026-04-12T09:03:00+09:00",
    category: "정책 갱신",
    updates: ["고객사 내부 검토 대기"],
  },
];

export const helpArticles: HelpArticle[] = [
  {
    id: "help-token-expired",
    title: "카카오 연결 만료 시 다시 연결하는 방법",
    category: "카카오 연동",
    summary: "연결 만료 오류가 발생하면 카카오 채널 정보를 확인하고 다시 연결해야 합니다.",
    relatedStatuses: ["token-expired", "reauth-required"],
    steps: [
      "카카오 채널 관리자 권한이 있는 계정으로 채널 정보를 확인합니다.",
      "카카오 연동 화면에서 채널 정보를 다시 확인합니다.",
      "연결 테스트를 실행해 마지막 검증 시각이 갱신되는지 확인합니다.",
    ],
  },
  {
    id: "help-missing-consent",
    title: "필수 개인정보 동의가 없을 때",
    category: "개인정보 동의",
    summary: "필수 동의가 제출되지 않으면 카카오 연동과 테스트 실행이 잠깁니다.",
    relatedStatuses: ["not-connected", "connecting"],
    steps: [
      "개인정보 동의 화면으로 이동합니다.",
      "필수 동의 항목을 모두 체크합니다.",
      "동의 버전과 제출 시각이 기록되었는지 확인합니다.",
    ],
  },
  {
    id: "help-permission",
    title: "권한 부족 오류 해결",
    category: "오류 복구",
    summary: "카카오 앱 권한이 부족하면 테스트 메시지와 실운영 메시지 전송이 모두 실패합니다.",
    relatedStatuses: ["insufficient-permission", "error"],
    steps: [
      "앱에 talk_message 등 필요한 scope가 포함되어 있는지 확인합니다.",
      "권한이 수정되면 연동 화면에서 재연결을 실행합니다.",
      "실패 로그에서 에러 코드가 사라졌는지 다시 확인합니다.",
    ],
  },
  {
    id: "help-webhook",
    title: "웹훅 연결 실패 점검",
    category: "웹훅",
    summary: "기존 접수 폼과의 연결 실패는 접수 폼 설정 오류나 외부 서버 지연이 원인인 경우가 많습니다.",
    relatedStatuses: ["connection-failed", "error"],
    steps: [
      "접수 폼 설정에서 FlowFit 연결 상태가 정상인지 확인합니다.",
      "방화벽이나 IP 허용 목록이 있으면 FlowFit 엔진 주소를 허용합니다.",
      "헬스 체크 재시도 후 응답 시간을 확인합니다.",
    ],
  },
];

export const customerNotes: Record<string, string> = {
  "cust-ora-clinic":
    "이번 주에 예약 부서에서 테스트를 직접 재실행할 예정. 카카오 재연결 후 1회 확인 콜이 필요합니다.",
  "cust-jayu-education":
    "고객사 내부 보안 담당자의 승인 지연으로 scope 반영이 늦어지고 있습니다.",
  "cust-daejin-logistics":
    "처음 운영 도입 단계라 체크리스트 위주 안내가 가장 효과적입니다.",
};

export const adminSettings: AdminSettings = {
  badgeRules: {
    warningThreshold: 2,
    criticalThreshold: 5,
  },
  exceptionInboxLinks: [
    {
      id: "exc-1",
      keyword: "환불",
      url: "https://intake.flowfit.mock/exception/refund",
      description: "환불 요청 예외 접수 폼",
      enabled: true,
    },
    {
      id: "exc-2",
      keyword: "취소",
      url: "https://intake.flowfit.mock/exception/cancel",
      description: "예약 취소 예외 접수 폼",
      enabled: true,
    },
    {
      id: "exc-3",
      keyword: "분쟁",
      url: "https://intake.flowfit.mock/exception/dispute",
      description: "고객 분쟁 처리 접수 폼",
      enabled: false,
    },
  ],
  notificationRules: [
    {
      id: "notif-1",
      title: "카카오 재인증 필요",
      condition: "카카오 연동 상태가 reauth-required로 변경될 때",
      channel: "이메일 + 관리자 대시보드",
      enabled: true,
    },
    {
      id: "notif-2",
      title: "24시간 테스트 실패율 경고",
      condition: "최근 24시간 실패율이 20% 이상일 때",
      channel: "슬랙 + 관리자 대시보드",
      enabled: true,
    },
    {
      id: "notif-3",
      title: "개인정보 동의 만료 예정",
      condition: "동의 버전이 최신이 아니거나 만료 예정일 때",
      channel: "이메일",
      enabled: true,
    },
  ],
  defaultTestTemplate:
    "[플로우핏 테스트] 고객님의 연동 상태를 확인하는 테스트 메시지입니다. 본 메시지를 수신했다면 기본 연결은 정상입니다.",
  consentVersions: [
    {
      version: "v2026.04",
      releasedAt: "2026-04-01T09:00:00+09:00",
      active: true,
    },
    {
      version: "v2026.03",
      releasedAt: "2026-03-01T09:00:00+09:00",
      active: false,
    },
  ],
  roleNotes: [
    "customer 역할은 자기 조직 데이터와 실행 화면만 접근 가능합니다.",
    "admin 역할은 전체 고객사 상태, 실패 로그, 티켓, 정책 설정에 접근 가능합니다.",
    "수동 재실행과 티켓 생성은 관리자만 수행할 수 있습니다.",
  ],
};
