import {
  calculateFormConfidence,
  detectIntakeType,
  extractFieldsFromIntake,
  findMissingFields,
  getDetectedTypeLabel,
} from "@/services/intakeAiClassifier";
import { makeFlowFitId } from "@/services/fieldIntakeStore";
import type { AutoGeneratedIntakeForm, AutoGeneratedIntakeFormStatus, RawFieldIntake } from "@/types/flowfit";

const AUTO_INTAKE_FORM_STORAGE_KEY = "flowfit-auto-intake-forms";

function nowIso() {
  return new Date().toISOString();
}

function readJson<T>(key: string, fallback: T): T {
  if (typeof window === "undefined") return fallback;

  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

function writeJson<T>(key: string, value: T) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(key, JSON.stringify(value));
}

function makeQuestion(missingField: string) {
  if (missingField === "상품명") {
    return {
      question: "상품명이 기존 납품 상품과 동일한가요?",
      options: ["기존 상품과 동일", "사진에 있음", "직접 입력 필요", "잘 모르겠음"],
    };
  }

  if (missingField === "주문번호") {
    return {
      question: "고객 주문번호를 확인할 수 있나요?",
      options: ["주문번호 확인됨", "고객에게 확인 필요", "담당자 확인 중"],
    };
  }

  return {
    question: `${missingField} 정보를 확인해주세요.`,
    options: ["확인됨", "확인 중", "잘 모르겠음"],
  };
}

export function buildAutoGeneratedForm(intake: RawFieldIntake): AutoGeneratedIntakeForm {
  const now = nowIso();
  const detectedType = detectIntakeType(intake);
  const fields = extractFieldsFromIntake(intake, detectedType);
  const missingFields = findMissingFields(fields);
  const typeLabel = getDetectedTypeLabel(detectedType);
  const firstPartner = fields.find((item) => item.label.includes("거래처"))?.value;
  const title =
    detectedType === "purchase_order_document" && firstPartner
      ? `${firstPartner} 추가 주문 후보`
      : `${typeLabel} 판별 결과`;

  return {
    id: makeFlowFitId("auto-form"),
    companyId: intake.companyId,
    intakeId: intake.id,
    title,
    detectedType,
    rawInputSummary: intake.rawText || "첨부 자료 중심의 현장 접수입니다.",
    fields,
    missingFields,
    suggestedQuestions: missingFields.map((missingField) => ({
      id: makeFlowFitId("question"),
      ...makeQuestion(missingField),
    })),
    aiSummary: `${typeLabel}로 보이는 현장 접수입니다. 평균 신뢰도 ${Math.round(
      calculateFormConfidence(fields) * 100,
    )}%이며, 대표 확인 전에는 공식 처리에 사용할 수 없습니다.`,
    aiWarnings: missingFields.length
      ? [`부족 정보: ${missingFields.join(", ")}`, "대표 승인 전 외부 발송과 정식 처리에는 사용할 수 없습니다."]
      : ["대표 승인 전 외부 발송과 정식 처리에는 사용할 수 없습니다."],
    status: "ready_for_owner_review",
    createdAt: now,
    updatedAt: now,
  };
}

export const initialAutoGeneratedIntakeForms: AutoGeneratedIntakeForm[] = [
  {
    ...buildAutoGeneratedForm({
      id: "field-intake-a-order",
      companyId: "flowfit-demo",
      submittedByName: "김직원",
      rawText: "A거래처 3박스 더 달라고 함. 내일까지 가능한지 물어봄.",
      imageUrls: ["placeholder:purchase-order"],
      fileUrls: [],
      urgency: "today",
      clientCreatedAt: "2026-04-29T09:10:00+09:00",
      serverReceivedAt: "2026-04-29T09:11:00+09:00",
      status: "waiting_owner_review",
      createdAt: "2026-04-29T09:11:00+09:00",
      updatedAt: "2026-04-29T09:13:00+09:00",
    }),
    id: "auto-form-a-order",
    createdAt: "2026-04-29T09:12:00+09:00",
    updatedAt: "2026-04-29T09:13:00+09:00",
  },
  {
    ...buildAutoGeneratedForm({
      id: "field-intake-b-receipt",
      companyId: "flowfit-demo",
      submittedByName: "박직원",
      rawText: "현장에서 입금했다고 영수증 보여줌.",
      imageUrls: ["placeholder:receipt"],
      fileUrls: [],
      urgency: "normal",
      clientCreatedAt: "2026-04-29T10:18:00+09:00",
      serverReceivedAt: "2026-04-29T10:20:00+09:00",
      status: "waiting_owner_review",
      createdAt: "2026-04-29T10:20:00+09:00",
      updatedAt: "2026-04-29T10:22:00+09:00",
    }),
    id: "auto-form-b-receipt",
    createdAt: "2026-04-29T10:21:00+09:00",
    updatedAt: "2026-04-29T10:22:00+09:00",
  },
  {
    ...buildAutoGeneratedForm({
      id: "field-intake-c-complaint",
      companyId: "flowfit-demo",
      submittedByName: "이직원",
      rawText: "고객이 배송 늦는다고 화냄. 오늘 중 연락 달라 함.",
      imageUrls: [],
      fileUrls: [],
      urgency: "urgent",
      clientCreatedAt: "2026-04-29T11:04:00+09:00",
      serverReceivedAt: "2026-04-29T11:04:00+09:00",
      status: "waiting_owner_review",
      createdAt: "2026-04-29T11:04:00+09:00",
      updatedAt: "2026-04-29T11:06:00+09:00",
    }),
    id: "auto-form-c-complaint",
    createdAt: "2026-04-29T11:05:00+09:00",
    updatedAt: "2026-04-29T11:06:00+09:00",
  },
];

export function getAutoGeneratedIntakeForms() {
  return readJson(AUTO_INTAKE_FORM_STORAGE_KEY, initialAutoGeneratedIntakeForms);
}

export function saveAutoGeneratedIntakeForms(forms: AutoGeneratedIntakeForm[]) {
  writeJson(AUTO_INTAKE_FORM_STORAGE_KEY, forms);
}

export function createAutoGeneratedIntakeForm(intake: RawFieldIntake) {
  const form = buildAutoGeneratedForm(intake);
  saveAutoGeneratedIntakeForms([form, ...getAutoGeneratedIntakeForms()]);
  return form;
}

export function updateAutoGeneratedIntakeForm(
  formId: string,
  updater: (form: AutoGeneratedIntakeForm) => AutoGeneratedIntakeForm,
) {
  const nextForms = getAutoGeneratedIntakeForms().map((form) => (form.id === formId ? updater(form) : form));
  saveAutoGeneratedIntakeForms(nextForms);
  return nextForms;
}

export function setAutoGeneratedFormStatus(formId: string, status: AutoGeneratedIntakeFormStatus) {
  return updateAutoGeneratedIntakeForm(formId, (form) => ({
    ...form,
    status,
    updatedAt: nowIso(),
  }));
}
