import { calculateFormConfidence, mapDetectedTypeToBusinessEvent } from "@/services/intakeAiClassifier";
import { makeFlowFitId } from "@/services/fieldIntakeStore";
import type {
  AutoGeneratedIntakeForm,
  BusinessContextEvent,
  RawFieldIntake,
  VerificationStatus,
} from "@/types/flowfit";

const BUSINESS_CONTEXT_STORAGE_KEY = "flowfit-business-context-events";

function nowIso() {
  return new Date().toISOString();
}

function readJson<T>(key: string, fallback: T): T {
  if (typeof window === "undefined") return fallback;

  try {
    const raw = window.localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : fallback;
  } catch {
    return fallback;
  }
}

function writeJson<T>(key: string, value: T) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(key, JSON.stringify(value));
}

function buildEventFromForm(intake: RawFieldIntake, form: AutoGeneratedIntakeForm): BusinessContextEvent {
  const now = nowIso();
  return {
    id: makeFlowFitId("business-event"),
    companyId: intake.companyId,
    eventType: mapDetectedTypeToBusinessEvent(form.detectedType),
    title: form.title,
    summary: form.aiSummary,
    source: "field_intake",
    sourceId: intake.id,
    confidence: calculateFormConfidence(form.fields),
    verificationStatus: form.missingFields.length ? "needs_more_info" : "unverified",
    extractedFacts: form.fields.map((field) => ({
      key: field.label,
      value: String(field.value ?? "확인 필요"),
      confidence: field.confidence,
      sourceText: intake.rawText,
    })),
    usableForAiPlanning: true,
    usableForExternalAction: false,
    createdAt: now,
    updatedAt: now,
  };
}

export const initialBusinessContextEvents: BusinessContextEvent[] = [
  {
    ...buildEventFromForm(
      {
        id: "field-intake-a-order",
        companyId: "flowfit-demo",
        rawText: "A거래처 3박스 더 달라고 함. 내일까지 가능한지 물어봄.",
        imageUrls: ["placeholder:purchase-order"],
        fileUrls: [],
        urgency: "today",
        clientCreatedAt: "2026-04-29T09:10:00+09:00",
        serverReceivedAt: "2026-04-29T09:11:00+09:00",
        status: "waiting_owner_review",
        createdAt: "2026-04-29T09:11:00+09:00",
        updatedAt: "2026-04-29T09:13:00+09:00",
      },
      {
        id: "auto-form-a-order",
        companyId: "flowfit-demo",
        intakeId: "field-intake-a-order",
        title: "A거래처 추가 주문 후보",
        detectedType: "purchase_order_document",
        rawInputSummary: "A거래처 3박스 더 달라고 함. 내일까지 가능한지 물어봄.",
        fields: [
          { id: "field-a-partner", label: "거래처", type: "text", required: true, value: "A거래처", source: "ai_extracted", confidence: 0.92 },
          { id: "field-a-quantity", label: "수량", type: "text", required: true, value: "3박스", source: "ai_extracted", confidence: 0.78 },
          { id: "field-a-due", label: "희망 납기", type: "date", required: true, value: "내일", source: "ai_extracted", confidence: 0.86 },
          { id: "field-a-product", label: "상품명", type: "text", required: true, value: "확인 필요", source: "needs_confirmation", confidence: 0.22 },
        ],
        missingFields: ["상품명"],
        suggestedQuestions: [],
        aiSummary: "발주서 후보로 보이는 현장 접수입니다.",
        aiWarnings: ["상품명 확인 필요"],
        status: "ready_for_owner_review",
        createdAt: "2026-04-29T09:12:00+09:00",
        updatedAt: "2026-04-29T09:13:00+09:00",
      },
    ),
    id: "business-event-a-order",
    verificationStatus: "needs_more_info",
    createdAt: "2026-04-29T09:12:00+09:00",
    updatedAt: "2026-04-29T09:13:00+09:00",
  },
  {
    id: "business-event-b-receipt",
    companyId: "flowfit-demo",
    eventType: "receipt_candidate",
    title: "영수증 판별 결과",
    summary: "입금 영수증으로 보이는 자료입니다. 금전 정보라 공식 기록으로 승격해도 회계 확인이 필요합니다.",
    source: "field_intake",
    sourceId: "field-intake-b-receipt",
    confidence: 0.65,
    verificationStatus: "needs_more_info",
    extractedFacts: [
      { key: "거래처", value: "B거래처", confidence: 0.81, sourceText: "현장에서 입금했다고 영수증 보여줌." },
      { key: "금액", value: "320000", confidence: 0.69, sourceText: "현장에서 입금했다고 영수증 보여줌." },
      { key: "입금 여부", value: "확인 필요", confidence: 0.44, sourceText: "현장에서 입금했다고 영수증 보여줌." },
    ],
    usableForAiPlanning: true,
    usableForExternalAction: false,
    createdAt: "2026-04-29T10:21:00+09:00",
    updatedAt: "2026-04-29T10:22:00+09:00",
  },
  {
    id: "business-event-c-complaint",
    companyId: "flowfit-demo",
    eventType: "customer_complaint_candidate",
    title: "고객 클레임 판별 결과",
    summary: "배송 지연 불만으로 보이는 긴급 접수입니다. 고객 응대 전 주문번호 확인이 필요합니다.",
    source: "field_intake",
    sourceId: "field-intake-c-complaint",
    confidence: 0.65,
    verificationStatus: "needs_more_info",
    extractedFacts: [
      { key: "고객 불만", value: "높음", confidence: 0.88, sourceText: "고객이 배송 늦는다고 화냄. 오늘 중 연락 달라 함." },
      { key: "요청", value: "오늘 중 연락", confidence: 0.83, sourceText: "고객이 배송 늦는다고 화냄. 오늘 중 연락 달라 함." },
      { key: "주문번호", value: "확인 필요", confidence: 0.24, sourceText: "고객이 배송 늦는다고 화냄. 오늘 중 연락 달라 함." },
    ],
    usableForAiPlanning: true,
    usableForExternalAction: false,
    createdAt: "2026-04-29T11:05:00+09:00",
    updatedAt: "2026-04-29T11:06:00+09:00",
  },
];

export function getBusinessContextEvents() {
  return readJson(BUSINESS_CONTEXT_STORAGE_KEY, initialBusinessContextEvents);
}

export function saveBusinessContextEvents(events: BusinessContextEvent[]) {
  writeJson(BUSINESS_CONTEXT_STORAGE_KEY, events);
}

export function createBusinessContextEvent(intake: RawFieldIntake, form: AutoGeneratedIntakeForm) {
  const event = buildEventFromForm(intake, form);
  saveBusinessContextEvents([event, ...getBusinessContextEvents()]);
  return event;
}

export function updateBusinessContextEvent(
  eventId: string,
  updater: (event: BusinessContextEvent) => BusinessContextEvent,
) {
  const nextEvents = getBusinessContextEvents().map((event) => (event.id === eventId ? updater(event) : event));
  saveBusinessContextEvents(nextEvents);
  return nextEvents;
}

export function setBusinessContextVerificationStatus(eventId: string, verificationStatus: VerificationStatus) {
  return updateBusinessContextEvent(eventId, (event) => ({
    ...event,
    verificationStatus,
    updatedAt: nowIso(),
  }));
}
