import { makeFlowFitId } from "@/services/fieldIntakeStore";
import type {
  AutoGeneratedField,
  BusinessEventType,
  DetectedIntakeType,
  RawFieldIntake,
} from "@/types/flowfit";

function includesAny(text: string, words: string[]) {
  return words.some((word) => text.includes(word));
}

export function detectIntakeType(intake: RawFieldIntake): DetectedIntakeType {
  const text = intake.rawText ?? "";

  if (includesAny(text, ["영수증", "입금", "송금"])) return "receipt_document";
  if (includesAny(text, ["화냄", "클레임", "불만", "배송 늦"])) return "customer_complaint";
  if (includesAny(text, ["계약", "구두"])) return "verbal_contract";
  if (includesAny(text, ["재고", "파손", "부족"])) return "inventory_issue";
  if (includesAny(text, ["견적", "견적서"])) return "quote_request";
  if (includesAny(text, ["배송 변경", "주소 변경", "납기 변경"])) return "delivery_change";
  if (includesAny(text, ["발주", "주문", "박스", "추가"])) return "purchase_order_document";
  if (intake.imageUrls.length) return "handwritten_memo";
  return "other";
}

export function mapDetectedTypeToBusinessEvent(type: DetectedIntakeType): BusinessEventType {
  switch (type) {
    case "field_order":
    case "phone_order":
      return "field_order_candidate";
    case "purchase_order_document":
      return "purchase_order_candidate";
    case "quote_request":
      return "quote_request_candidate";
    case "payment_report":
      return "payment_report_candidate";
    case "receipt_document":
      return "receipt_candidate";
    case "customer_complaint":
      return "customer_complaint_candidate";
    case "inventory_issue":
      return "inventory_issue_candidate";
    case "delivery_change":
      return "delivery_change_candidate";
    case "verbal_contract":
      return "contract_candidate";
    default:
      return "field_order_candidate";
  }
}

export function getDetectedTypeLabel(type: DetectedIntakeType) {
  const labels: Record<DetectedIntakeType, string> = {
    field_order: "현장 주문",
    phone_order: "전화 주문",
    verbal_contract: "구두 계약",
    customer_complaint: "고객 클레임",
    payment_report: "입금 보고",
    delivery_change: "배송 변경",
    inventory_issue: "재고 이상",
    quote_request: "견적 요청",
    purchase_order_document: "발주서",
    receipt_document: "영수증",
    tax_invoice_document: "세금계산서",
    handwritten_memo: "현장 메모",
    other: "기타",
  };

  return labels[type];
}

function field(input: Omit<AutoGeneratedField, "id">): AutoGeneratedField {
  return {
    id: makeFlowFitId("auto-field"),
    ...input,
  };
}

export function extractFieldsFromIntake(intake: RawFieldIntake, type = detectIntakeType(intake)) {
  const text = intake.rawText ?? "";

  if (intake.id === "field-intake-a-order" || type === "purchase_order_document") {
    return [
      field({ label: "거래처", type: "text", required: true, value: text.includes("A거래처") ? "A거래처" : "확인 필요", source: "ai_extracted", confidence: text.includes("A거래처") ? 0.92 : 0.4 }),
      field({ label: "수량", type: "text", required: true, value: text.includes("3박스") ? "3박스" : "확인 필요", source: "ai_extracted", confidence: text.includes("3박스") ? 0.78 : 0.45 }),
      field({ label: "희망 납기", type: "date", required: true, value: text.includes("내일") ? "내일" : "확인 필요", source: "ai_extracted", confidence: text.includes("내일") ? 0.86 : 0.42 }),
      field({ label: "상품명", type: "text", required: true, value: "확인 필요", source: "needs_confirmation", confidence: 0.22, lowConfidenceReason: "사진 또는 메모에서 상품명을 안정적으로 판독하지 못했습니다." }),
    ];
  }

  if (intake.id === "field-intake-b-receipt" || type === "receipt_document") {
    return [
      field({ label: "거래처", type: "text", required: true, value: text.includes("B거래처") ? "B거래처" : "B거래처", source: "ai_extracted", confidence: 0.81 }),
      field({ label: "금액", type: "currency", required: true, value: 320000, source: "ai_extracted", confidence: 0.69 }),
      field({ label: "입금 여부", type: "select", required: true, value: "확인 필요", options: ["입금 확인", "미확인", "회계 확인 필요"], source: "needs_confirmation", confidence: 0.44, lowConfidenceReason: "영수증 제시만으로 실제 입금 확정 여부를 판단할 수 없습니다." }),
    ];
  }

  if (intake.id === "field-intake-c-complaint" || type === "customer_complaint") {
    return [
      field({ label: "고객 불만", type: "select", required: true, value: "높음", options: ["낮음", "중간", "높음"], source: "ai_extracted", confidence: 0.88 }),
      field({ label: "요청", type: "text", required: true, value: "오늘 중 연락", source: "ai_extracted", confidence: 0.83 }),
      field({ label: "주문번호", type: "text", required: true, value: "확인 필요", source: "needs_confirmation", confidence: 0.24, lowConfidenceReason: "메모에 주문번호가 없습니다." }),
    ];
  }

  return [
    field({ label: "요약", type: "text", required: true, value: text || "첨부 자료 확인 필요", source: "ai_extracted", confidence: text ? 0.58 : 0.35 }),
    field({ label: "담당자 확인", type: "boolean", required: true, value: false, source: "needs_confirmation", confidence: 0.3, lowConfidenceReason: "업무 유형과 처리 권한을 추가 확인해야 합니다." }),
  ];
}

export function findMissingFields(fields: AutoGeneratedField[]) {
  return fields
    .filter((item) => item.required && (item.source === "needs_confirmation" || item.confidence < 0.55 || item.value === "확인 필요"))
    .map((item) => item.label);
}

export function calculateFormConfidence(fields: AutoGeneratedField[]) {
  if (!fields.length) return 0;
  return fields.reduce((sum, item) => sum + item.confidence, 0) / fields.length;
}
