import { getAiWorkItems, saveAiWorkItems } from "@/services/aiWorkStore";
import { getAutoGeneratedIntakeForms, saveAutoGeneratedIntakeForms } from "@/services/autoIntakeFormEngine";
import { getBusinessContextEvents, saveBusinessContextEvents } from "@/services/businessContextStore";
import { getRawFieldIntakes, makeFlowFitId, saveRawFieldIntakes } from "@/services/fieldIntakeStore";
import { getOfficialCompanyRecords, saveOfficialCompanyRecords } from "@/services/officialRecordStore";
import { createStaffRequest } from "@/services/staffRequestStore";
import type {
  AiWorkItem,
  AutoGeneratedIntakeForm,
  BusinessContextEvent,
  OfficialCompanyRecord,
  OfficialRecordStatus,
  OfficialRecordType,
  RawFieldIntake,
  RiskLevel,
  StaffConfirmationRequest,
} from "@/types/flowfit";

function nowIso() {
  return new Date().toISOString();
}

function mapRecordType(event: BusinessContextEvent): OfficialRecordType {
  switch (event.eventType) {
    case "field_order_candidate":
      return "order_candidate";
    case "purchase_order_candidate":
      return "order_candidate";
    case "quote_request_candidate":
      return "quote_request";
    case "payment_report_candidate":
    case "receipt_candidate":
      return "payment_candidate";
    case "customer_complaint_candidate":
      return "customer_complaint";
    case "inventory_issue_candidate":
      return "inventory_issue";
    case "delivery_change_candidate":
      return "delivery_change";
    case "contract_candidate":
      return "contract_candidate";
    default:
      return "task";
  }
}

function getRiskLevel(recordType: OfficialRecordType): RiskLevel {
  if (recordType === "payment_candidate" || recordType === "contract_candidate") return "high";
  if (recordType === "customer_complaint") return "medium";
  if (recordType === "order_candidate" || recordType === "delivery_change") return "medium";
  return "low";
}

function getRecordStatus(recordType: OfficialRecordType): OfficialRecordStatus {
  if (recordType === "payment_candidate" || recordType === "contract_candidate") {
    return "pending_secondary_review";
  }

  return "active";
}

function canUseForExternalAction(recordType: OfficialRecordType, riskLevel: RiskLevel) {
  if (riskLevel === "high") return false;
  return recordType === "order_candidate" || recordType === "delivery_change";
}

function buildStructuredData(form: AutoGeneratedIntakeForm, correctedData?: Record<string, string | number | boolean | null>) {
  const extracted = form.fields.reduce<Record<string, string | number | boolean | null>>((acc, field) => {
    acc[field.label] = field.value ?? null;
    return acc;
  }, {});

  return {
    ...extracted,
    ...(correctedData ?? {}),
  };
}

function buildFollowUpAiWork(record: OfficialCompanyRecord): AiWorkItem {
  const now = nowIso();
  const workType =
    record.recordType === "customer_complaint"
      ? "customer_reply"
      : record.recordType === "payment_candidate"
        ? "staff_confirmation"
        : "order_check";

  const resultTitle =
    record.recordType === "customer_complaint"
      ? "고객 응대 초안 생성"
      : record.recordType === "payment_candidate"
        ? "회계 확인 요청"
        : "후속 확인 작업";

  const resultContent =
    record.recordType === "payment_candidate"
      ? "입금 관련 정보는 공식 기록 후보로 저장되었으며, 회계 확인 후 최종 처리해야 합니다."
      : `${record.title} 정보를 바탕으로 후속 업무를 준비합니다.`;

  return {
    id: makeFlowFitId("ai-work-official-record"),
    companyId: record.companyId,
    title: `${record.title} 후속 처리`,
    type: workType,
    status: "waiting_approval",
    riskLevel: record.riskLevel,
    approvalPolicy: record.riskLevel === "high" ? "owner_only" : "approval_required",
    sourceType: "system",
    sourceSummary: `공식 회사 정보: ${record.title}`,
    requestedByUserId: record.approvedByUserId,
    requestedByName: record.approvedByName,
    aiReasonSummary:
      "대표가 수락한 공식 회사 정보만 강한 근거로 사용했습니다. 원본 임시 정보와 AI 정리 후보는 단독으로 확정 처리하지 않습니다.",
    resultTitle,
    resultContent,
    previewMessage: "예외 접수함에서 공식 정보로 승격된 기록과 연결된 후속 작업입니다.",
    instructionHistory: [],
    steps: [
      { id: makeFlowFitId("step"), label: "공식 회사 정보 확인", status: "done" },
      { id: makeFlowFitId("step"), label: "후속 업무 후보 생성", status: "done" },
      { id: makeFlowFitId("step"), label: "대표 승인 대기", status: "running" },
    ],
    executionPreview: {
      serviceName: "FlowFit 공식 정보 저장소",
      screenName: record.title,
      safeActionSummary: ["대표 승인 완료 기록만 AI 판단 근거로 읽었습니다."],
      lastUpdatedAt: now,
    },
    createdAt: now,
    updatedAt: now,
  };
}

export function acceptIntakeAsOfficialRecord(
  intakeId: string,
  options?: {
    correctedData?: Record<string, string | number | boolean | null>;
    approvedByName?: string;
  },
) {
  const now = nowIso();
  const intakes = getRawFieldIntakes();
  const forms = getAutoGeneratedIntakeForms();
  const events = getBusinessContextEvents();
  const records = getOfficialCompanyRecords();

  const intake = intakes.find((item) => item.id === intakeId);
  const form = forms.find((item) => item.intakeId === intakeId || item.id === intake?.aiFormId);
  const event = events.find((item) => item.sourceId === intakeId || item.id === intake?.businessContextEventId);

  if (!intake || !form || !event) {
    return { intakes, forms, events, records, works: getAiWorkItems(), record: null };
  }

  const recordType = mapRecordType(event);
  const riskLevel = getRiskLevel(recordType);
  const record: OfficialCompanyRecord = {
    id: makeFlowFitId("official-record"),
    companyId: intake.companyId,
    recordType,
    status: getRecordStatus(recordType),
    title: form.title,
    summary:
      recordType === "payment_candidate" || recordType === "contract_candidate"
        ? `${form.aiSummary} 금전/계약 정보라 2차 검토 상태로 저장합니다.`
        : form.aiSummary,
    sourceEventId: event.id,
    sourceIntakeId: intake.id,
    approvedByUserId: "owner-demo",
    approvedByName: options?.approvedByName ?? "대표",
    approvedAt: now,
    correctedByOwner: Boolean(options?.correctedData),
    structuredData: buildStructuredData(form, options?.correctedData),
    riskLevel,
    usableForAiPlanning: true,
    usableForExternalAction: canUseForExternalAction(recordType, riskLevel),
    createdAt: now,
    updatedAt: now,
  };

  const nextRecords = [record, ...records];
  const nextIntakes = intakes.map((item) =>
    item.id === intakeId
      ? { ...item, status: "converted" as const, officialRecordId: record.id, updatedAt: now }
      : item,
  );
  const nextForms = forms.map((item) =>
    item.id === form.id
      ? {
          ...item,
          status: options?.correctedData ? ("owner_corrected" as const) : ("converted" as const),
          fields: item.fields.map((field) =>
            options?.correctedData && Object.prototype.hasOwnProperty.call(options.correctedData, field.label)
              ? {
                  ...field,
                  value: options.correctedData[field.label] ?? field.value,
                  source: "owner_corrected" as const,
                  confidence: 1,
                }
              : field,
          ),
          updatedAt: now,
        }
      : item,
  );
  const nextEvents = events.map((item) =>
    item.id === event.id
      ? {
          ...item,
          verificationStatus: "owner_approved" as const,
          usableForAiPlanning: true,
          usableForExternalAction: record.usableForExternalAction,
          officialRecordId: record.id,
          updatedAt: now,
        }
      : item,
  );
  const followUpWork = buildFollowUpAiWork(record);
  const nextWorks = [followUpWork, ...getAiWorkItems()];

  saveRawFieldIntakes(nextIntakes);
  saveAutoGeneratedIntakeForms(nextForms);
  saveBusinessContextEvents(nextEvents);
  saveOfficialCompanyRecords(nextRecords);
  saveAiWorkItems(nextWorks);

  return {
    intakes: nextIntakes,
    forms: nextForms,
    events: nextEvents,
    records: nextRecords,
    works: nextWorks,
    record,
  };
}

export function requestStaffRecheckForIntake(
  intakeId: string,
  input?: {
    title?: string;
    question?: string;
    staffName?: string;
  },
) {
  const intakes = getRawFieldIntakes();
  const forms = getAutoGeneratedIntakeForms();
  const events = getBusinessContextEvents();
  const intake = intakes.find((item) => item.id === intakeId);
  const form = forms.find((item) => item.intakeId === intakeId || item.id === intake?.aiFormId);

  if (!intake || !form) return null;

  const question = input?.question ?? form.suggestedQuestions[0]?.question ?? "방금 접수한 건의 부족 정보를 확인해주세요.";
  const request: StaffConfirmationRequest = createStaffRequest({
    aiWorkId: `field-intake:${intakeId}`,
    title: input?.title ?? form.title,
    question,
    internalReason: `예외 접수 ${form.title}의 부족 정보(${form.missingFields.join(", ") || "추가 확인"}) 확인이 필요합니다.`,
    requestedByName: "대표",
    staffName: input?.staffName ?? intake.submittedByName ?? "현장 직원",
  });

  const now = nowIso();
  const nextIntakes = intakes.map((item) =>
    item.id === intakeId ? { ...item, status: "needs_more_info" as const, updatedAt: now } : item,
  );
  const nextForms = forms.map((item) =>
    item.id === form.id ? { ...item, status: "needs_staff_input" as const, updatedAt: now } : item,
  );
  const nextEvents = events.map((item) =>
    item.sourceId === intakeId ? { ...item, verificationStatus: "needs_more_info" as const, updatedAt: now } : item,
  );

  saveRawFieldIntakes(nextIntakes);
  saveAutoGeneratedIntakeForms(nextForms);
  saveBusinessContextEvents(nextEvents);

  return request;
}

export function applyStaffRecheckResponseToIntake(intakeId: string, response: string) {
  const now = nowIso();
  const intakes = getRawFieldIntakes();
  const forms = getAutoGeneratedIntakeForms();
  const events = getBusinessContextEvents();
  const intake = intakes.find((item) => item.id === intakeId);
  const form = forms.find((item) => item.intakeId === intakeId || item.id === intake?.aiFormId);

  if (!intake || !form) return { intakes, forms, events };

  const missing = form.missingFields[0] ?? "직원 확인";
  const nextForms = forms.map((item) =>
    item.id === form.id
      ? {
          ...item,
          status: "ready_for_owner_review" as const,
          missingFields: item.missingFields.filter((field) => field !== missing),
          fields: item.fields.map((field) =>
            field.label === missing || field.source === "needs_confirmation"
              ? { ...field, value: response, source: "user_input" as const, confidence: Math.max(field.confidence, 0.74) }
              : field,
          ),
          aiWarnings: [`직원 재확인 응답이 들어왔습니다: ${response}`],
          updatedAt: now,
        }
      : item,
  );
  const nextIntakes = intakes.map((item) =>
    item.id === intakeId ? { ...item, status: "waiting_owner_review" as const, updatedAt: now } : item,
  );
  const nextEvents = events.map((item) =>
    item.sourceId === intakeId
      ? {
          ...item,
          verificationStatus: "manager_reviewed" as const,
          extractedFacts: [
            ...item.extractedFacts.filter((fact) => fact.key !== missing),
            { key: missing, value: response, confidence: 0.74, sourceText: "직원 재확인 응답" },
          ],
          updatedAt: now,
        }
      : item,
  );

  saveRawFieldIntakes(nextIntakes);
  saveAutoGeneratedIntakeForms(nextForms);
  saveBusinessContextEvents(nextEvents);

  return { intakes: nextIntakes, forms: nextForms, events: nextEvents };
}

export function rejectFieldIntake(intakeId: string) {
  return updateReviewStatus(intakeId, "rejected", "cancelled", "rejected");
}

export function holdFieldIntake(intakeId: string) {
  return updateReviewStatus(intakeId, "on_hold", "ready_for_owner_review", "unverified");
}

function updateReviewStatus(
  intakeId: string,
  intakeStatus: RawFieldIntake["status"],
  formStatus: AutoGeneratedIntakeForm["status"],
  verificationStatus: BusinessContextEvent["verificationStatus"],
) {
  const now = nowIso();
  const intakes = getRawFieldIntakes();
  const forms = getAutoGeneratedIntakeForms();
  const events = getBusinessContextEvents();
  const intake = intakes.find((item) => item.id === intakeId);

  const nextIntakes = intakes.map((item) =>
    item.id === intakeId ? { ...item, status: intakeStatus, updatedAt: now } : item,
  );
  const nextForms = forms.map((item) =>
    item.intakeId === intakeId || item.id === intake?.aiFormId ? { ...item, status: formStatus, updatedAt: now } : item,
  );
  const nextEvents = events.map((item) =>
    item.sourceId === intakeId || item.id === intake?.businessContextEventId
      ? { ...item, verificationStatus, usableForExternalAction: false, updatedAt: now }
      : item,
  );

  saveRawFieldIntakes(nextIntakes);
  saveAutoGeneratedIntakeForms(nextForms);
  saveBusinessContextEvents(nextEvents);

  return { intakes: nextIntakes, forms: nextForms, events: nextEvents, records: getOfficialCompanyRecords() };
}
