"use client";

import { AlertCircle, CheckCircle2, LockKeyhole, ShieldAlert } from "lucide-react";

import { AutoGeneratedFormPreview } from "@/components/flowfit/AutoGeneratedFormPreview";
import { OfficialRecordPreview } from "@/components/flowfit/OfficialRecordPreview";
import { OwnerReviewActions } from "@/components/flowfit/OwnerReviewActions";
import { RawIntakeCard } from "@/components/flowfit/RawIntakeCard";
import { StaffRecheckRequestPanel } from "@/components/flowfit/StaffRecheckRequestPanel";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  acceptIntakeAsOfficialRecord,
  applyStaffRecheckResponseToIntake,
  holdFieldIntake,
  rejectFieldIntake,
  requestStaffRecheckForIntake,
} from "@/services/ownerReviewService";
import type {
  AutoGeneratedIntakeForm,
  BusinessContextEvent,
  OfficialCompanyRecord,
  RawFieldIntake,
  StaffConfirmationRequest,
} from "@/types/flowfit";

const statusLabels: Record<RawFieldIntake["status"], string> = {
  uploaded: "원본 접수",
  ai_processing: "AI 판별 중",
  form_generated: "대표 확인 대기",
  needs_more_info: "정보 부족",
  waiting_owner_review: "대표 확인 대기",
  converted: "공식 정보 전환",
  rejected: "반려",
  on_hold: "보류",
};

function getStatusVariant(status: RawFieldIntake["status"]) {
  if (status === "converted") return "success" as const;
  if (status === "rejected") return "danger" as const;
  if (status === "needs_more_info" || status === "on_hold") return "warning" as const;
  return "info" as const;
}

export function AiIntakeReviewCard({
  intake,
  form,
  event,
  record,
  staffRequest,
  onRefresh,
}: {
  intake: RawFieldIntake;
  form?: AutoGeneratedIntakeForm;
  event?: BusinessContextEvent;
  record?: OfficialCompanyRecord;
  staffRequest?: StaffConfirmationRequest;
  onRefresh: (message?: string) => void;
}) {
  const actionDisabled = intake.status === "converted" || intake.status === "rejected";

  if (!form) {
    return (
      <Card>
        <CardContent className="p-5">
          <Badge variant="warning">AI 판별 대기</Badge>
          <p className="mt-3 text-sm text-slate-600">원본은 접수되었고 AI 임시 폼 생성이 필요합니다.</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-panel">
      <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant={getStatusVariant(intake.status)}>{statusLabels[intake.status]}</Badge>
            <Badge>검토 대기 정보</Badge>
            {event?.verificationStatus === "owner_approved" ? <Badge variant="success">대표 승인 완료</Badge> : null}
          </div>
          <h2 className="mt-3 text-xl font-semibold text-slate-950">{form.title}</h2>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
            현장 원본은 바로 공식 정보가 되지 않습니다. 대표가 수락한 정보만 AI 업무 판단과 후속 처리의 강한 근거로 사용됩니다.
          </p>
        </div>
        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm lg:w-[22rem]">
          <p className="inline-flex items-center gap-2 font-semibold text-slate-950">
            <LockKeyhole className="h-4 w-4" />
            정보 등급
          </p>
          <div className="mt-2 grid gap-1 text-xs text-slate-600">
            <span>[1] 원본 임시 정보: 공식 처리 불가</span>
            <span>[2] AI 정리 정보: 후보 정보</span>
            <span>[3] 검토 대기 정보: 외부 발송 불가</span>
            <span className={record ? "font-semibold text-emerald-700" : ""}>[4] 확정 정보: 대표 수락 후 사용</span>
          </div>
        </div>
      </div>

      <div className="mt-5 grid gap-4 xl:grid-cols-[0.85fr_1.15fr]">
        <RawIntakeCard intake={intake} />
        <AutoGeneratedFormPreview form={form} />
      </div>

      <div className="mt-4 grid gap-4 xl:grid-cols-[1fr_1fr]">
        <OfficialRecordPreview form={form} event={event} record={record} />
        <Card>
          <CardContent className="space-y-3 p-4">
            <p className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950">
              <ShieldAlert className="h-4 w-4" />
              현재 AI 사용 가능 범위
            </p>
            <div className="grid gap-1 text-sm text-slate-600">
              <span>{event?.usableForAiPlanning ? "[✓] 내부 참고 가능" : "[ ] 내부 참고 불가"}</span>
              <span>{event?.usableForExternalAction ? "[조건부] 외부 실행 승인 필요" : "[ ] 외부 발송 사용 불가"}</span>
              <span>{record ? "[✓] 후속 AI 작업 생성됨" : "[ ] 정식 처리 불가"}</span>
            </div>
            {form.aiWarnings.length ? (
              <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3">
                <p className="inline-flex items-center gap-2 text-xs font-semibold text-amber-800">
                  <AlertCircle className="h-3.5 w-3.5" />
                  AI 경고
                </p>
                <div className="mt-1 space-y-1">
                  {form.aiWarnings.map((warning) => (
                    <p key={warning} className="text-sm text-amber-900">
                      {warning}
                    </p>
                  ))}
                </div>
              </div>
            ) : null}
          </CardContent>
        </Card>
      </div>

      {staffRequest ? (
        <div className="mt-4">
          <StaffRecheckRequestPanel
            request={staffRequest}
            onRespond={(response) => {
              applyStaffRecheckResponseToIntake(intake.id, response);
              onRefresh("직원 재확인 응답이 회수되어 대표 확인 대기로 돌아왔습니다.");
            }}
          />
        </div>
      ) : null}

      <div className="mt-5 rounded-3xl border border-slate-200 bg-slate-50 p-4">
        {record ? (
          <div className="flex items-center gap-2 text-sm font-semibold text-emerald-700">
            <CheckCircle2 className="h-4 w-4" />
            공식 회사 정보로 승격되었습니다. AI 작업 승인함에 후속 작업이 생성되었습니다.
          </div>
        ) : (
          <OwnerReviewActions
            disabled={actionDisabled}
            missingFields={form.missingFields}
            onAccept={() => {
              acceptIntakeAsOfficialRecord(intake.id);
              onRefresh("공식 회사 정보로 수락했고 AI 작업 승인함에 후속 작업을 만들었습니다.");
            }}
            onAcceptWithCorrection={(correction) => {
              acceptIntakeAsOfficialRecord(intake.id, { correctedData: correction });
              onRefresh("수정 후 공식 회사 정보로 수락했습니다.");
            }}
            onRecheck={(question) => {
              requestStaffRecheckForIntake(intake.id, { question });
              onRefresh("직원 재확인 요청을 만들었습니다.");
            }}
            onReject={() => {
              rejectFieldIntake(intake.id);
              onRefresh("예외 접수를 반려했습니다.");
            }}
            onHold={() => {
              holdFieldIntake(intake.id);
              onRefresh("예외 접수를 보류했습니다.");
            }}
          />
        )}
      </div>
    </article>
  );
}
