import { AlertTriangle, CheckCircle2, HelpCircle } from "lucide-react";

import { ConfidenceBadge } from "@/components/flowfit/ConfidenceBadge";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { getDetectedTypeLabel } from "@/services/intakeAiClassifier";
import type { AutoGeneratedIntakeForm } from "@/types/flowfit";

export function AutoGeneratedFormPreview({ form }: { form: AutoGeneratedIntakeForm }) {
  return (
    <Card>
      <CardContent className="space-y-4 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant="info">AI 정리 정보</Badge>
          <Badge>{getDetectedTypeLabel(form.detectedType)}</Badge>
        </div>

        <div>
          <p className="text-xs font-semibold text-slate-400">AI 판별</p>
          <h3 className="mt-1 text-lg font-semibold text-slate-950">{form.title}</h3>
          <p className="mt-2 text-sm leading-6 text-slate-600">{form.aiSummary}</p>
        </div>

        <div className="space-y-2">
          <p className="text-xs font-semibold text-slate-400">AI가 추출한 핵심 정보</p>
          {form.fields.map((field) => (
            <div key={field.id} className="rounded-2xl border border-slate-200 bg-white p-3">
              <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                <div>
                  <p className="text-sm font-semibold text-slate-950">{field.label}</p>
                  <p className="mt-1 text-sm text-slate-600">{String(field.value ?? "확인 필요")}</p>
                </div>
                <ConfidenceBadge confidence={field.confidence} />
              </div>
              {field.lowConfidenceReason ? (
                <p className="mt-2 text-xs leading-5 text-rose-600">{field.lowConfidenceReason}</p>
              ) : null}
            </div>
          ))}
        </div>

        <div className="rounded-2xl border border-amber-200 bg-amber-50 p-3">
          <p className="inline-flex items-center gap-2 text-sm font-semibold text-amber-800">
            <AlertTriangle className="h-4 w-4" />
            부족 정보
          </p>
          <div className="mt-2 flex flex-wrap gap-2">
            {form.missingFields.length ? (
              form.missingFields.map((field) => (
                <Badge key={field} variant="warning">
                  {field}
                </Badge>
              ))
            ) : (
              <span className="inline-flex items-center gap-1 text-sm text-emerald-700">
                <CheckCircle2 className="h-4 w-4" /> 추가 부족 정보 없음
              </span>
            )}
          </div>
        </div>

        {form.suggestedQuestions.length ? (
          <div className="rounded-2xl border border-sky-200 bg-sky-50 p-3">
            <p className="inline-flex items-center gap-2 text-sm font-semibold text-sky-800">
              <HelpCircle className="h-4 w-4" />
              추천 질문
            </p>
            <div className="mt-2 space-y-2">
              {form.suggestedQuestions.map((question) => (
                <div key={question.id}>
                  <p className="text-sm text-sky-950">{question.question}</p>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {question.options?.map((option) => (
                      <span key={option} className="rounded-full bg-white px-2 py-1 text-xs font-medium text-sky-700">
                        {option}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        ) : null}
      </CardContent>
    </Card>
  );
}
