"use client";

import { BellRing, CheckCircle2, ClipboardList, FileWarning, Inbox, RefreshCcw } from "lucide-react";
import * as React from "react";

import { AiIntakeReviewCard } from "@/components/flowfit/AiIntakeReviewCard";
import { FlowFitRoleControl, RestrictedEmployeeView, canUseAiOperations, useFlowFitRole } from "@/components/flowfit/flowfit-access";
import { IntakeAccessManager } from "@/components/flowfit/IntakeAccessManager";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { cn, formatNumber } from "@/lib/utils";
import { getAutoGeneratedIntakeForms } from "@/services/autoIntakeFormEngine";
import { getBusinessContextEvents } from "@/services/businessContextStore";
import { getRawFieldIntakes } from "@/services/fieldIntakeStore";
import { getOfficialCompanyRecords } from "@/services/officialRecordStore";
import { getStaffRequests } from "@/services/staffRequestStore";
import type {
  AutoGeneratedIntakeForm,
  BusinessContextEvent,
  OfficialCompanyRecord,
  RawFieldIntake,
  RawFieldIntakeStatus,
  StaffConfirmationRequest,
} from "@/types/flowfit";

type ExceptionTab =
  | "all"
  | "uploaded"
  | "ai_processing"
  | "waiting_owner_review"
  | "needs_more_info"
  | "converted"
  | "rejected"
  | "on_hold";

const tabs: Array<{ id: ExceptionTab; label: string; statuses?: RawFieldIntakeStatus[] }> = [
  { id: "all", label: "전체" },
  { id: "uploaded", label: "원본 접수", statuses: ["uploaded"] },
  { id: "ai_processing", label: "AI 판별 중", statuses: ["ai_processing"] },
  { id: "waiting_owner_review", label: "대표 확인 대기", statuses: ["form_generated", "waiting_owner_review"] },
  { id: "needs_more_info", label: "정보 부족", statuses: ["needs_more_info"] },
  { id: "converted", label: "공식 정보 전환", statuses: ["converted"] },
  { id: "rejected", label: "반려", statuses: ["rejected"] },
  { id: "on_hold", label: "보류", statuses: ["on_hold"] },
];

function countByStatuses(items: RawFieldIntake[], statuses: RawFieldIntakeStatus[]) {
  return items.filter((item) => statuses.includes(item.status)).length;
}

function findForm(forms: AutoGeneratedIntakeForm[], intake: RawFieldIntake) {
  return forms.find((form) => form.intakeId === intake.id || form.id === intake.aiFormId);
}

function findEvent(events: BusinessContextEvent[], intake: RawFieldIntake) {
  return events.find((event) => event.sourceId === intake.id || event.id === intake.businessContextEventId);
}

function findRecord(records: OfficialCompanyRecord[], intake: RawFieldIntake) {
  return records.find((record) => record.id === intake.officialRecordId || record.sourceIntakeId === intake.id);
}

function findStaffRequest(requests: StaffConfirmationRequest[], intake: RawFieldIntake) {
  return requests.find((request) => request.aiWorkId === `field-intake:${intake.id}`);
}

export function ExceptionInbox() {
  const { role, setRole } = useFlowFitRole();
  const [activeTab, setActiveTab] = React.useState<ExceptionTab>("waiting_owner_review");
  const [intakes, setIntakes] = React.useState<RawFieldIntake[]>([]);
  const [forms, setForms] = React.useState<AutoGeneratedIntakeForm[]>([]);
  const [events, setEvents] = React.useState<BusinessContextEvent[]>([]);
  const [records, setRecords] = React.useState<OfficialCompanyRecord[]>([]);
  const [staffRequests, setStaffRequests] = React.useState<StaffConfirmationRequest[]>([]);
  const [notice, setNotice] = React.useState("[FlowFit 확인 필요] 현장 접수 자료가 대표 확인을 기다리고 있습니다.");

  const refresh = React.useCallback((message?: string) => {
    setIntakes(getRawFieldIntakes());
    setForms(getAutoGeneratedIntakeForms());
    setEvents(getBusinessContextEvents());
    setRecords(getOfficialCompanyRecords());
    setStaffRequests(getStaffRequests());
    if (message) setNotice(message);
  }, []);

  React.useEffect(() => {
    refresh();
  }, [refresh]);

  if (!canUseAiOperations(role)) {
    return (
      <div className="space-y-4">
        <FlowFitRoleControl role={role} onChange={setRole} />
        <RestrictedEmployeeView />
      </div>
    );
  }

  const currentTab = tabs.find((tab) => tab.id === activeTab);
  const visibleIntakes =
    activeTab === "all" || !currentTab?.statuses
      ? intakes
      : intakes.filter((intake) => currentTab.statuses?.includes(intake.status));
  const waitingCount = countByStatuses(intakes, ["waiting_owner_review", "form_generated"]);
  const summary = [
    { label: "대표 확인 대기", value: waitingCount, icon: BellRing },
    { label: "정보 부족", value: countByStatuses(intakes, ["needs_more_info"]), icon: FileWarning },
    { label: "공식 전환", value: countByStatuses(intakes, ["converted"]), icon: CheckCircle2 },
    { label: "전체 접수", value: intakes.length, icon: ClipboardList },
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="muted-caption">예외 접수함</p>
          <h1 className="mt-2 text-3xl font-semibold text-slate-950">현장 자료를 공식 회사 정보로 승격합니다</h1>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">
            직원이 올린 사진, 음성, 메모, 파일은 원본 임시 정보입니다. AI가 정리하고 대표가 확인한 정보만 공식 기록이 됩니다.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <FlowFitRoleControl role={role} onChange={setRole} />
          <Button type="button" variant="outline" size="sm" onClick={() => refresh("예외 접수함을 새로고침했습니다.")}>
            <RefreshCcw className="h-4 w-4" />
            새로고침
          </Button>
        </div>
      </div>

      <Card className="border-sky-200 bg-sky-50">
        <CardContent className="flex flex-col gap-3 p-5 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <p className="inline-flex items-center gap-2 text-sm font-semibold text-sky-900">
              <BellRing className="h-4 w-4" />
              {notice}
            </p>
            <p className="mt-1 text-sm text-sky-800">
              AI 판별: 거래처, 수량, 납기, 불확실 항목을 비교하고 대표 액션을 선택하세요.
            </p>
          </div>
          <Badge variant="info">{waitingCount}건 확인 필요</Badge>
        </CardContent>
      </Card>

      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        {summary.map((item) => {
          const Icon = item.icon;
          return (
            <Card key={item.label}>
              <CardContent className="flex items-center justify-between gap-3 p-5">
                <div>
                  <p className="text-sm text-slate-500">{item.label}</p>
                  <p className="mt-2 text-2xl font-semibold text-slate-950">{formatNumber(item.value)}</p>
                </div>
                <div className="rounded-2xl bg-slate-100 p-3 text-slate-600">
                  <Icon className="h-5 w-5" />
                </div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <IntakeAccessManager />

      <Card>
        <CardContent className="p-5">
          <div className="flex gap-2 overflow-x-auto pb-2">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab.id)}
                className={cn(
                  "inline-flex shrink-0 items-center gap-2 rounded-full border px-3 py-2 text-sm font-semibold transition",
                  activeTab === tab.id
                    ? "border-slate-950 bg-slate-950 text-white"
                    : "border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:text-slate-950",
                )}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="space-y-5">
        {visibleIntakes.length ? (
          visibleIntakes.map((intake) => (
            <AiIntakeReviewCard
              key={intake.id}
              intake={intake}
              form={findForm(forms, intake)}
              event={findEvent(events, intake)}
              record={findRecord(records, intake)}
              staffRequest={findStaffRequest(staffRequests, intake)}
              onRefresh={refresh}
            />
          ))
        ) : (
          <Card>
            <CardContent className="p-10 text-center">
              <Inbox className="mx-auto h-8 w-8 text-slate-400" />
              <p className="mt-3 font-semibold text-slate-950">해당 상태의 예외 접수가 없습니다</p>
              <p className="mt-1 text-sm text-slate-500">현장 접수가 들어오면 AI 판별 카드가 이곳에 표시됩니다.</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
