"use client";

import { Camera, CheckCircle2, FileText, ImagePlus, Mic, Send, ShieldCheck } from "lucide-react";
import * as React from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { createAutoGeneratedIntakeForm } from "@/services/autoIntakeFormEngine";
import { createBusinessContextEvent } from "@/services/businessContextStore";
import { createRawFieldIntake, updateRawFieldIntake } from "@/services/fieldIntakeStore";
import { validateIntakeAccess } from "@/services/intakeAccessService";
import type { FieldIntakeAccess, IntakeUrgency } from "@/types/flowfit";

const allowedFileExtensions = [".jpg", ".jpeg", ".png", ".webp", ".pdf", ".m4a", ".mp3", ".wav"];
const maxFileSize = 10 * 1024 * 1024;

function fileToken(file: File, prefix: string) {
  return `${prefix}:${file.name}`;
}

function validateFiles(files: File[]) {
  const invalid = files.find((file) => {
    const lower = file.name.toLowerCase();
    const allowed = allowedFileExtensions.some((extension) => lower.endsWith(extension));
    return !allowed || file.size > maxFileSize;
  });

  if (!invalid) return null;

  return "허용되지 않는 파일이 있거나 10MB를 초과했습니다.";
}

export function FieldQuickIntakePage({
  companySlug,
  token,
}: {
  companySlug: string;
  token?: string;
}) {
  const [sessionChecked, setSessionChecked] = React.useState(false);
  const [intakeAuthenticated, setIntakeAuthenticated] = React.useState(false);
  const [access, setAccess] = React.useState<{
    ok: boolean;
    companyId: string;
    staffId?: string;
    staffName?: string;
    access?: FieldIntakeAccess;
  } | null>(null);
  const [staffId, setStaffId] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [loginError, setLoginError] = React.useState("");
  const [loginSubmitting, setLoginSubmitting] = React.useState(false);
  const [memo, setMemo] = React.useState("");
  const [urgency, setUrgency] = React.useState<IntakeUrgency>("normal");
  const [photos, setPhotos] = React.useState<File[]>([]);
  const [files, setFiles] = React.useState<File[]>([]);
  const [voice, setVoice] = React.useState<File | null>(null);
  const [error, setError] = React.useState("");
  const [submittedTitle, setSubmittedTitle] = React.useState("");
  const cameraInputRef = React.useRef<HTMLInputElement | null>(null);
  const photoLibraryInputRef = React.useRef<HTMLInputElement | null>(null);

  React.useEffect(() => {
    async function checkSession() {
      const params = new URLSearchParams({ companySlug });
      if (token) params.set("token", token);
      const response = await fetch(`/api/auth/intake-session?${params.toString()}`, {
        credentials: "include",
      }).catch(() => null);
      const data = (await response?.json().catch(() => null)) as {
        authenticated?: boolean;
        companyId?: string;
        staffId?: string;
        staffName?: string;
      } | null;
      const authenticated = Boolean(data?.authenticated);
      setIntakeAuthenticated(authenticated);
      setAccess(
        authenticated
          ? {
              ok: true,
              companyId: data?.companyId ?? validateIntakeAccess(companySlug, token).companyId,
              staffId: data?.staffId,
              staffName: data?.staffName,
            }
          : null,
      );
      setSessionChecked(true);
    }

    void checkSession();
  }, [companySlug, token]);

  async function handleLogin(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setLoginError("");
    setLoginSubmitting(true);

    try {
      const response = await fetch("/api/auth/intake-login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({
          companySlug,
          token,
          staffId: staffId.trim(),
          password,
        }),
      });

      if (!response.ok) {
        setLoginError("직원 ID 또는 비밀번호가 올바르지 않습니다.");
        return;
      }

      const data = (await response.json().catch(() => null)) as {
        companyId?: string;
        staffId?: string;
        staffName?: string;
      } | null;
      setIntakeAuthenticated(true);
      setAccess({
        ok: true,
        companyId: data?.companyId ?? validateIntakeAccess(companySlug, token).companyId,
        staffId: data?.staffId ?? staffId.trim(),
        staffName: data?.staffName,
      });
      setPassword("");
    } finally {
      setLoginSubmitting(false);
    }
  }

  function addPhotos(fileList: FileList | null) {
    const nextPhotos = Array.from(fileList ?? []);
    if (!nextPhotos.length) return;
    setPhotos((current) => [...current, ...nextPhotos]);
  }

  if (!sessionChecked) {
    return <div className="min-h-screen bg-slate-50" />;
  }

  if (!intakeAuthenticated) {
    return (
      <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10">
        <div className="mx-auto max-w-lg">
          <div className="mb-5 rounded-3xl border border-slate-200 bg-white p-5 text-center shadow-panel">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-slate-950 text-white">
              <ShieldCheck className="h-5 w-5" />
            </div>
            <h1 className="mt-4 text-3xl font-semibold text-slate-950">FlowFit 직원 접수 로그인</h1>
            <p className="mt-2 text-sm leading-6 text-slate-600">
              직원 ID와 비밀번호를 확인한 뒤, 접수 전용 업로드 화면만 열립니다.
            </p>
          </div>

          <Card>
            <CardContent className="space-y-4 p-5">
              <div className="flex flex-wrap gap-2">
                <Badge variant="success">업로드 전용</Badge>
                <Badge>회사 데이터 조회 불가</Badge>
              </div>

              <form onSubmit={handleLogin} className="space-y-4">
                <label className="block">
                  <span className="text-sm font-semibold text-slate-950">직원 ID</span>
                  <Input
                    value={staffId}
                    onChange={(event) => setStaffId(event.target.value)}
                    autoComplete="username"
                    className="mt-2"
                    placeholder="예: kim"
                  />
                </label>

                <label className="block">
                  <span className="text-sm font-semibold text-slate-950">비밀번호</span>
                  <Input
                    type="password"
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    autoComplete="current-password"
                    className="mt-2"
                  />
                </label>

                {loginError ? <p className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{loginError}</p> : null}

                <Button type="submit" className="w-full" disabled={loginSubmitting || !staffId.trim() || !password}>
                  <ShieldCheck className="h-4 w-4" />
                  접수 화면 열기
                </Button>
              </form>

              <p className="text-xs leading-5 text-slate-500">
                직원 ID/비밀번호는 URL이나 localStorage에 저장하지 않습니다. 서버가 확인한 HTTP-only 세션으로만 접수 화면을 엽니다.
              </p>
            </CardContent>
          </Card>
        </div>
      </main>
    );
  }

  if (!access) {
    return <div className="min-h-screen bg-slate-50" />;
  }

  if (!access.ok) {
    return (
      <main className="min-h-screen bg-slate-50 px-4 py-10">
        <Card className="mx-auto max-w-lg">
          <CardContent className="p-8 text-center">
            <Badge variant="danger">접수 링크 만료</Badge>
            <h1 className="mt-4 text-2xl font-semibold text-slate-950">사용할 수 없는 접수 링크입니다</h1>
            <p className="mt-2 text-sm leading-6 text-slate-600">토큰이 만료되었거나 폐기되었습니다. 담당자에게 새 링크를 요청하세요.</p>
          </CardContent>
        </Card>
      </main>
    );
  }

  const validatedAccess = access;

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    const allFiles = [...photos, ...files, ...(voice ? [voice] : [])];
    const validationMessage = validateFiles(allFiles);

    if (validationMessage) {
      setError(validationMessage);
      return;
    }

    if (!memo.trim() && allFiles.length === 0) {
      setError("사진, 파일, 음성, 메모 중 하나는 남겨주세요.");
      return;
    }

    const intake = createRawFieldIntake({
      companyId: validatedAccess.companyId,
      submittedByName: validatedAccess.staffName ?? "외부 현장 직원",
      rawText: memo.trim(),
      imageUrls: photos.map((file) => fileToken(file, "uploaded-photo")),
      fileUrls: files.map((file) => fileToken(file, "uploaded-file")),
      voiceMemoUrl: voice ? fileToken(voice, "uploaded-voice") : undefined,
      urgency,
      userAgent: navigator.userAgent,
    });
    const form = createAutoGeneratedIntakeForm(intake);
    const businessEvent = createBusinessContextEvent(intake, form);

    updateRawFieldIntake(intake.id, (item) => ({
      ...item,
      status: "waiting_owner_review",
      aiFormId: form.id,
      businessContextEventId: businessEvent.id,
      updatedAt: new Date().toISOString(),
    }));

    setSubmittedTitle(form.title);
    setMemo("");
    setUrgency("normal");
    setPhotos([]);
    setFiles([]);
    setVoice(null);
  }

  return (
    <main className="min-h-screen bg-slate-50 px-4 py-6 sm:py-10">
      <div className="mx-auto max-w-3xl">
        <div className="mb-5 rounded-3xl border border-slate-200 bg-white p-5 shadow-panel">
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant="info">업로드 전용</Badge>
            <Badge>회사 데이터 조회 불가</Badge>
          </div>
          <h1 className="mt-3 text-3xl font-semibold text-slate-950">FlowFit 빠른 접수</h1>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            사진, 파일, 음성, 짧은 메모만 남기면 AI가 정리한 뒤 대표님 승인함에 올라갑니다.
          </p>
        </div>

        {submittedTitle ? (
          <Card className="mb-5 border-emerald-200 bg-emerald-50">
            <CardContent className="p-5">
              <p className="inline-flex items-center gap-2 font-semibold text-emerald-800">
                <CheckCircle2 className="h-5 w-5" />
                접수 완료
              </p>
              <p className="mt-2 text-sm leading-6 text-emerald-900">
                {submittedTitle} 건으로 AI가 정리했습니다. 대표님이 확인한 뒤 공식 회사 정보로 저장됩니다.
              </p>
            </CardContent>
          </Card>
        ) : null}

        <form onSubmit={handleSubmit} className="space-y-4">
          <Card>
            <CardContent className="space-y-5 p-5">
              <div className="grid gap-3 sm:grid-cols-2">
                <div className="rounded-2xl border border-slate-200 bg-white p-4 sm:col-span-2">
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                    <span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950">
                    <Camera className="h-4 w-4" />
                    사진 찍기
                    </span>
                    {photos.length ? (
                      <span className="text-xs font-semibold text-slate-500">선택된 사진 {photos.length}장</span>
                    ) : null}
                  </div>
                  <p className="mt-2 text-xs leading-5 text-slate-500">
                    현장에서는 즉석 촬영을 누르면 휴대폰 카메라가 바로 열립니다. 이미 찍어둔 사진은 앨범에서 첨부하세요.
                  </p>

                  <div className="mt-3 grid gap-2 sm:grid-cols-2">
                    <Button type="button" onClick={() => cameraInputRef.current?.click()}>
                      <Camera className="h-4 w-4" />
                      즉석 촬영
                    </Button>
                    <Button type="button" variant="outline" onClick={() => photoLibraryInputRef.current?.click()}>
                      <ImagePlus className="h-4 w-4" />
                      앨범에서 첨부
                    </Button>
                  </div>
                  <Input
                    ref={cameraInputRef}
                    type="file"
                    accept="image/*"
                    capture="environment"
                    className="sr-only"
                    onChange={(event) => {
                      addPhotos(event.target.files);
                      event.currentTarget.value = "";
                    }}
                  />
                  <Input
                    ref={photoLibraryInputRef}
                    type="file"
                    accept="image/*"
                    multiple
                    className="sr-only"
                    onChange={(event) => {
                      addPhotos(event.target.files);
                      event.currentTarget.value = "";
                    }}
                  />

                  {photos.length ? (
                    <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 p-3">
                      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                        <p className="text-xs font-semibold text-slate-500">
                          {photos
                            .slice(0, 2)
                            .map((photo) => photo.name)
                            .join(", ")}
                          {photos.length > 2 ? ` 외 ${photos.length - 2}장` : ""}
                        </p>
                        <Button type="button" variant="ghost" size="sm" onClick={() => setPhotos([])}>
                          사진 초기화
                        </Button>
                      </div>
                    </div>
                  ) : null}
                </div>
                <label className="rounded-2xl border border-slate-200 bg-white p-4">
                  <span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950">
                    <FileText className="h-4 w-4" />
                    파일 첨부
                  </span>
                  <Input
                    type="file"
                    accept=".jpg,.jpeg,.png,.webp,.pdf"
                    multiple
                    className="mt-3"
                    onChange={(event) => setFiles(Array.from(event.target.files ?? []))}
                  />
                </label>
                <label className="rounded-2xl border border-slate-200 bg-white p-4">
                  <span className="inline-flex items-center gap-2 text-sm font-semibold text-slate-950">
                    <Mic className="h-4 w-4" />
                    음성으로 말하기
                  </span>
                  <Input
                    type="file"
                    accept="audio/*"
                    capture
                    className="mt-3"
                    onChange={(event) => setVoice(event.target.files?.[0] ?? null)}
                  />
                </label>
                <label className="rounded-2xl border border-slate-200 bg-white p-4">
                  <span className="text-sm font-semibold text-slate-950">긴급도</span>
                  <Select value={urgency} onChange={(event) => setUrgency(event.target.value as IntakeUrgency)} className="mt-3">
                    <option value="normal">보통</option>
                    <option value="today">오늘 처리</option>
                    <option value="urgent">긴급</option>
                  </Select>
                </label>
              </div>

              <label className="block">
                <span className="text-sm font-semibold text-slate-950">짧은 메모 남기기</span>
                <Textarea
                  value={memo}
                  onChange={(event) => setMemo(event.target.value)}
                  placeholder="예: A거래처 3박스 더 달라고 함. 내일까지 가능한지 물어봄."
                  className="mt-2 min-h-[120px]"
                />
              </label>

              {error ? <p className="rounded-2xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}

              <Button type="submit" className="w-full">
                <Send className="h-4 w-4" />
                AI에게 정리 맡기기
              </Button>
            </CardContent>
          </Card>
        </form>

        <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-4">
          <p className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500">
            <ShieldCheck className="h-3.5 w-3.5" />
            이 화면에서는 업로드만 가능하며 회사 기록, AI 판단, 대표 승인함은 표시하지 않습니다.
          </p>
        </div>
      </div>
    </main>
  );
}
