import { ShieldCheck } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { AutoGeneratedIntakeForm, BusinessContextEvent, OfficialCompanyRecord } from "@/types/flowfit";

const eventRecordLabels: Record<BusinessContextEvent["eventType"], string> = {
  field_order_candidate: "주문 후보",
  quote_request_candidate: "견적 요청 기록",
  payment_report_candidate: "입금 확인 후보",
  customer_complaint_candidate: "고객 클레임 기록",
  inventory_issue_candidate: "재고 이상 기록",
  delivery_change_candidate: "배송 변경 기록",
  contract_candidate: "계약 후보",
  purchase_order_candidate: "주문 후보",
  receipt_candidate: "입금 확인 후보",
};

export function OfficialRecordPreview({
  form,
  event,
  record,
}: {
  form: AutoGeneratedIntakeForm;
  event?: BusinessContextEvent;
  record?: OfficialCompanyRecord;
}) {
  const title = record?.title ?? form.title;
  const label = record ? record.recordType : event ? eventRecordLabels[event.eventType] : "공식 기록 후보";
  const status = record?.status === "pending_secondary_review" ? "2차 검토 필요" : record ? "공식 정보" : "대표 수락 전 후보";

  return (
    <Card>
      <CardContent className="space-y-3 p-4">
        <div className="flex flex-wrap items-center gap-2">
          <Badge variant={record ? "success" : "default"}>{status}</Badge>
          <Badge>{label}</Badge>
        </div>
        <div>
          <p className="text-xs font-semibold text-slate-400">생성될 공식 회사 정보</p>
          <p className="mt-1 text-base font-semibold text-slate-950">{title}</p>
          <p className="mt-2 text-sm leading-6 text-slate-600">
            {record?.summary ?? "대표가 수락해야만 공식 회사 정보가 되며, 그 이후 AI 업무 판단의 강한 근거로 사용됩니다."}
          </p>
        </div>
        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-3">
          <p className="inline-flex items-center gap-2 text-sm font-semibold text-slate-900">
            <ShieldCheck className="h-4 w-4" />
            AI 사용 범위
          </p>
          <div className="mt-2 grid gap-1 text-sm text-slate-600">
            <span>[✓] 내부 참고 가능</span>
            <span>{record ? "[✓] 후속 작업 생성 가능" : "[ ] 대표 승인 전 후속 작업 생성 불가"}</span>
            <span>
              {record?.usableForExternalAction ? "[조건부] 외부 실행은 승인 필요" : "[ ] 외부 발송 사용 불가"}
            </span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
