export type UserRole = "owner" | "manager" | "employee" | "ai";

export type AiWorkType =
  | "customer_reply"
  | "order_check"
  | "inventory_check"
  | "report"
  | "staff_confirmation"
  | "external_message"
  | "reminder"
  | "automation"
  | "manual_request";

export type RiskLevel = "low" | "medium" | "high" | "uncertain";

export type ApprovalPolicy =
  | "auto_allowed"
  | "approval_required"
  | "owner_only"
  | "staff_confirmation_required";

export type AiWorkStatus =
  | "queued"
  | "collecting"
  | "analyzing"
  | "drafting"
  | "checking"
  | "waiting_approval"
  | "revision_needed"
  | "assigned_to_staff"
  | "completed"
  | "auto_completed"
  | "failed"
  | "cancelled";

export type AiWorkSourceType =
  | "sms"
  | "email"
  | "website"
  | "spreadsheet"
  | "manual"
  | "messenger"
  | "file"
  | "system";

export type AiWorkStepStatus = "done" | "running" | "pending" | "failed";

export interface AiWorkInstruction {
  id: string;
  userId: string;
  userName: string;
  instruction: string;
  createdAt: string;
}

export interface AiWorkStep {
  id: string;
  label: string;
  status: AiWorkStepStatus;
  summary?: string;
}

export interface AiExecutionPreview {
  serviceName?: string;
  screenName?: string;
  safeActionSummary?: string[];
  maskedScreenshotUrl?: string;
  lastUpdatedAt?: string;
}

export interface AiWorkItem {
  id: string;
  companyId: string;

  title: string;
  type: AiWorkType;
  status: AiWorkStatus;
  riskLevel: RiskLevel;
  approvalPolicy: ApprovalPolicy;

  sourceType: AiWorkSourceType;
  sourceSummary: string;

  requestedByUserId?: string;
  requestedByName?: string;

  aiReasonSummary: string;
  resultTitle: string;
  resultContent: string;

  previewMessage?: string;

  assignedStaffRequestId?: string;

  instructionHistory: AiWorkInstruction[];
  steps: AiWorkStep[];
  executionPreview?: AiExecutionPreview;

  createdAt: string;
  updatedAt: string;
  completedAt?: string;
}

export type StaffRequestStatus =
  | "draft"
  | "waiting_approval"
  | "sent"
  | "responded"
  | "expired"
  | "cancelled";

export type StaffRequestChannel =
  | "sms"
  | "email"
  | "slack"
  | "teams"
  | "kakao_work"
  | "telegram"
  | "manual";

export interface StaffConfirmationRequest {
  id: string;
  companyId: string;
  aiWorkId: string;

  requestedByUserId: string;
  requestedByName: string;

  staffId?: string;
  staffName: string;
  staffContact?: string;

  channel: StaffRequestChannel;
  status: StaffRequestStatus;

  title: string;
  question: string;
  responseOptions: string[];

  messagePreview: string;
  internalReason: string;

  sentAt?: string;
  respondedAt?: string;
  response?: string;
  responseMemo?: string;

  externalMessageId?: string;

  createdAt: string;
  updatedAt: string;
}

export interface AutoProcessedRecord {
  id: string;
  aiWorkId: string;
  title: string;
  processedAt: string;
  source: string;
  result: string;
  reason: string;
  reversible: boolean;
  status: Extract<AiWorkStatus, "auto_completed">;
}

export type IntakeUrgency = "normal" | "today" | "urgent";

export type RawFieldIntakeStatus =
  | "uploaded"
  | "ai_processing"
  | "form_generated"
  | "needs_more_info"
  | "waiting_owner_review"
  | "converted"
  | "rejected"
  | "on_hold";

export type IntakeAccessType = "public_token" | "staff_login" | "manager_login";

export interface FieldIntakeAccess {
  id: string;
  companyId: string;
  staffId?: string;
  staffName?: string;

  tokenHash: string;
  accessType: IntakeAccessType;

  canUploadPhoto: boolean;
  canUploadVoice: boolean;
  canUploadFile: boolean;
  canWriteMemo: boolean;

  canViewOwnSubmittedOnly: boolean;
  canViewCompanyData: false;

  expiresAt?: string;
  revokedAt?: string;

  createdAt: string;
  updatedAt: string;
}

export interface RawFieldIntake {
  id: string;
  companyId: string;

  submittedByStaffId?: string;
  submittedByName?: string;

  rawText?: string;
  imageUrls: string[];
  voiceMemoUrl?: string;
  fileUrls: string[];

  urgency: IntakeUrgency;

  clientCreatedAt: string;
  serverReceivedAt: string;

  networkInfo?: {
    userAgent?: string;
    ipHash?: string;
  };

  status: RawFieldIntakeStatus;

  aiFormId?: string;
  businessContextEventId?: string;
  officialRecordId?: string;

  createdAt: string;
  updatedAt: string;
}

export type DynamicFieldType =
  | "text"
  | "number"
  | "date"
  | "select"
  | "photo"
  | "file"
  | "voice"
  | "boolean"
  | "currency";

export type FieldSource = "ai_extracted" | "user_input" | "needs_confirmation" | "owner_corrected";

export interface AutoGeneratedField {
  id: string;
  label: string;
  type: DynamicFieldType;
  required: boolean;

  value?: string | number | boolean;
  options?: string[];

  source: FieldSource;
  confidence: number;

  lowConfidenceReason?: string;
}

export type DetectedIntakeType =
  | "field_order"
  | "phone_order"
  | "verbal_contract"
  | "customer_complaint"
  | "payment_report"
  | "delivery_change"
  | "inventory_issue"
  | "quote_request"
  | "purchase_order_document"
  | "receipt_document"
  | "tax_invoice_document"
  | "handwritten_memo"
  | "other";

export type AutoGeneratedIntakeFormStatus =
  | "generated"
  | "needs_staff_input"
  | "ready_for_owner_review"
  | "owner_accepted"
  | "owner_corrected"
  | "converted"
  | "cancelled";

export interface AutoGeneratedIntakeForm {
  id: string;
  companyId: string;
  intakeId: string;

  title: string;
  detectedType: DetectedIntakeType;

  rawInputSummary: string;

  fields: AutoGeneratedField[];

  missingFields: string[];

  suggestedQuestions: {
    id: string;
    question: string;
    options?: string[];
  }[];

  aiSummary: string;
  aiWarnings: string[];

  status: AutoGeneratedIntakeFormStatus;

  createdAt: string;
  updatedAt: string;
}

export type BusinessEventType =
  | "field_order_candidate"
  | "quote_request_candidate"
  | "payment_report_candidate"
  | "customer_complaint_candidate"
  | "inventory_issue_candidate"
  | "delivery_change_candidate"
  | "contract_candidate"
  | "purchase_order_candidate"
  | "receipt_candidate";

export type VerificationStatus =
  | "unverified"
  | "needs_more_info"
  | "manager_reviewed"
  | "owner_approved"
  | "rejected";

export interface BusinessContextEvent {
  id: string;
  companyId: string;

  eventType: BusinessEventType;

  title: string;
  summary: string;

  source: "field_intake" | "messenger_bot" | "email" | "file" | "manual";
  sourceId: string;

  confidence: number;
  verificationStatus: VerificationStatus;

  extractedFacts: {
    key: string;
    value: string;
    confidence: number;
    sourceText?: string;
  }[];

  usableForAiPlanning: boolean;
  usableForExternalAction: boolean;

  officialRecordId?: string;

  createdAt: string;
  updatedAt: string;
}

export type OfficialRecordType =
  | "order"
  | "order_candidate"
  | "quote_request"
  | "contract_candidate"
  | "payment_candidate"
  | "inventory_issue"
  | "customer_complaint"
  | "delivery_change"
  | "task"
  | "message";

export type OfficialRecordStatus =
  | "active"
  | "pending_secondary_review"
  | "completed"
  | "cancelled"
  | "archived";

export interface OfficialCompanyRecord {
  id: string;
  companyId: string;

  recordType: OfficialRecordType;
  status: OfficialRecordStatus;

  title: string;
  summary: string;

  sourceEventId: string;
  sourceIntakeId?: string;

  approvedByUserId: string;
  approvedByName: string;
  approvedAt: string;

  correctedByOwner: boolean;

  structuredData: Record<string, string | number | boolean | null>;

  riskLevel: RiskLevel;

  usableForAiPlanning: true;
  usableForExternalAction: boolean;

  createdAt: string;
  updatedAt: string;
}
